import { chromium, type Browser, type CDPSession, type Page } from "playwright-core";
import type { BrowserAutomationClient, CdpEventHandler } from "./cdp-client";

type RuntimeResponse<T> = {
  result: { value?: T; description?: string };
  exceptionDetails?: { text?: string; exception?: { description?: string } };
};

function asRecord(value: unknown) {
  return value && typeof value === "object" ? value as Record<string, unknown> : {};
}

export async function withJackyunBrowserTimeout<T>(promise: Promise<T>, timeoutMs: number, operation: string): Promise<T> {
  if (!Number.isFinite(timeoutMs) || timeoutMs <= 0) throw new Error("浏览器操作超时必须为正数。");
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<never>((_resolve, reject) => {
        timer = setTimeout(() => {
          const error = new Error(`${operation} 超过 ${timeoutMs}ms，已停止等待。`);
          error.name = "JackyunBrowserTimeoutError";
          reject(error);
        }, timeoutMs);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/**
 * A Playwright-first adapter for the existing page scripts.  Page evaluation
 * and pointer input go through Playwright; the attached CDP session is only
 * used for page-native network/download evidence that Playwright does not
 * expose on legacy MiniUI exports.
 */
export class PlaywrightPageClient implements BrowserAutomationClient {
  constructor(readonly page: Page, private readonly session: CDPSession) {}

  on(method: string, handler: CdpEventHandler) {
    // Playwright CDPSession exposes protocol notifications through its generic
    // `event` channel.  Subscribing to a raw protocol name (for example
    // Network.requestWillBeSent) silently misses every event, which left the
    // export controller without the signed OSS URL after a successful click.
    const listener = (event: { method: string; params?: object }) => {
      if (event.method === method) handler(asRecord(event.params));
    };
    this.session.on("event", listener);
    return () => this.session.off("event", listener);
  }

  async send<T = Record<string, unknown>>(method: string, params: Record<string, unknown> = {}, timeoutMs = 60_000): Promise<T> {
    if (method === "Runtime.evaluate") {
      const expression = String(params.expression ?? "");
      const evaluation = this.page.evaluate(async (source) => {
        try {
          // The expressions are generated by this repository, never external input.
          const value = await (0, eval)(source);
          return { result: { value } };
        } catch (error) {
          const message = error instanceof Error ? error.stack ?? error.message : String(error);
          return { result: {}, exceptionDetails: { text: message, exception: { description: message } } };
        }
      }, expression) as Promise<RuntimeResponse<T>>;
      const response = await withJackyunBrowserTimeout(evaluation, timeoutMs, "Runtime.evaluate");
      return response as T;
    }
    if (method === "Input.dispatchMouseEvent") {
      const type = String(params.type ?? "");
      const x = Number(params.x ?? 0);
      const y = Number(params.y ?? 0);
      const button = String(params.button ?? "left") as "left" | "right" | "middle";
      if (type === "mouseMoved") await this.page.mouse.move(x, y);
      if (type === "mousePressed") await this.page.mouse.down({ button });
      if (type === "mouseReleased") await this.page.mouse.up({ button });
      return {} as T;
    }
    if (method === "Page.navigate") {
      await this.page.goto(String(params.url ?? ""), { waitUntil: "domcontentloaded", timeout: timeoutMs });
      return {} as T;
    }
    const send = this.session.send as unknown as (command: string, parameters?: Record<string, unknown>) => Promise<T>;
    return await withJackyunBrowserTimeout(send.call(this.session, method, params), timeoutMs, method);
  }

  close() {
    void this.session.detach().catch(() => undefined);
  }
}

export async function connectPlaywrightBrowser(port: number) {
  return chromium.connectOverCDP(`http://127.0.0.1:${port}`, { timeout: 10_000 });
}

export async function connectPlaywrightJackyunTarget(browser: Browser, options: {
  startUrl?: string;
  workerName?: string;
  /**
   * Some adjacent JD tools share this client.  Keeping the legacy Jackyun
   * default avoids changing their behaviour while allowing a JD domain to be
   * selected without opening an unnecessary second page.
   */
  targetUrlPattern?: RegExp;
  /** JD WareList has no MiniUI controls; disable this only for an explicit JD worker. */
  requireMini?: boolean;
} = {}) {
  const workerName = options.workerName ?? "codex-jackyun-worker";
  const targetUrlPattern = options.targetUrlPattern ?? /jackyun\.com/i;
  const requireMini = options.requireMini ?? true;
  const matchesTarget = (url: string) => {
    targetUrlPattern.lastIndex = 0;
    return targetUrlPattern.test(url);
  };
  const pages = browser.contexts().flatMap((context) => context.pages());
  let page: Page | undefined;
  for (const candidate of pages) {
    const name = await candidate.evaluate(() => window.name).catch(() => "");
    if (name === workerName) {
      const candidateUrl = candidate.url();
      const isOwnedBlankPage = Boolean(options.startUrl) && candidateUrl === "about:blank";
      if (!matchesTarget(candidateUrl) && !isOwnedBlankPage) continue;
      // worker page 也需要检查 mini 控件是否存在（grid 已初始化）
      try {
        const hasMini = await candidate.evaluate(() => {
          const browserWindow = window as typeof window & { mini?: unknown };
          return Boolean(browserWindow.mini || document.querySelector('[class*="mini-"]'));
        });
        if (!requireMini || hasMini) { page = candidate; break; }
      } catch { /* worker page 不可用，继续找其他 page */ }
    }
  }
  if (!page) {
    const jackyunPages = pages.filter((item) => matchesTarget(item.url()));
    // 优先选择有 mini 控件的 page（grid 已初始化的预热页面）
    for (const candidate of requireMini ? jackyunPages : []) {
      try {
        const hasMini = await candidate.evaluate(() => {
          const browserWindow = window as typeof window & { mini?: unknown };
          return Boolean(browserWindow.mini || document.querySelector('[class*="mini-"]'));
        });
        if (hasMini) { page = candidate; break; }
      } catch { /* ignore */ }
    }
    // 回退到第一个 jackyun page
    if (!page && requireMini && jackyunPages.length > 0) page = jackyunPages[0];
    // 最后回退到创建新 page
    if (!page) {
      const context = browser.contexts()[0];
      if (!context) throw new Error("专用 Chrome 中没有可用的浏览器上下文。");
      page = await context.newPage();
    }
    await page.evaluate((name) => { window.name = name; }, workerName);
  }
  if (options.startUrl && !matchesTarget(page.url())) {
    await page.goto(options.startUrl, { waitUntil: "domcontentloaded", timeout: 30_000 });
  }
  const context = page.context();
  return { page, client: new PlaywrightPageClient(page, await context.newCDPSession(page)) };
}
