# Generated by Django 5.2.17 on 2026-09-05 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiAgentProviderDispatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("dispatch_ordinal", models.BigIntegerField()),
                ("owner_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("model_id", models.TextField()),
                ("model_version", models.BigIntegerField()),
                ("tool_policy_digest", models.TextField()),
                ("request_digest", models.TextField()),
                ("state", models.TextField(default="calling")),
                ("lease_epoch", models.BigIntegerField()),
                (
                    "reserved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "provider_called_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_agent_provider_dispatches",
            },
        ),
        migrations.CreateModel(
            name="AiAgentToolDispatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("tool_call_ordinal", models.BigIntegerField()),
                ("provider_call_id", models.TextField()),
                ("tool_name", models.TextField()),
                ("arguments_json", models.TextField()),
                ("arguments_digest", models.TextField()),
                ("invocation_id", models.TextField()),
                ("state", models.TextField(default="calling")),
                ("lease_epoch", models.BigIntegerField()),
                (
                    "reserved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tool_called_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_agent_tool_dispatches",
            },
        ),
        migrations.CreateModel(
            name="AiChatRequestReceipts",
            fields=[
                ("cancel_requested", models.BooleanField(default=False)),
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("client_request_id", models.TextField()),
                ("request_digest", models.TextField()),
                ("status", models.TextField()),
                ("model_id", models.TextField(blank=True, null=True)),
                ("assistant_message_id", models.TextField(blank=True, null=True)),
                ("result_json", models.TextField(blank=True, null=True)),
                ("error_code", models.TextField(blank=True, null=True)),
                ("admitted_at", models.DateTimeField(blank=True, null=True)),
                ("provider_started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_chat_request_receipts",
            },
        ),
        migrations.CreateModel(
            name="AiConversations",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("model_id", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_conversations",
            },
        ),
        migrations.CreateModel(
            name="AiDataRevision",
            fields=[
                (
                    "domain",
                    models.CharField(
                        default="ai-assistant",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("source_digest", models.CharField(default="", max_length=64)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_data_revisions",
            },
        ),
        migrations.CreateModel(
            name="AiKnowledgeEntries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("source_type", models.TextField()),
                ("source_ref", models.TextField()),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("tags_json", models.TextField(default="[]")),
                ("allowed_roles_json", models.TextField(default="[]")),
                ("status", models.TextField(default="active")),
                ("version", models.BigIntegerField(default=1)),
                ("content_digest", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_knowledge_entries",
            },
        ),
        migrations.CreateModel(
            name="AiMemoryAuditLogs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("operation_id", models.TextField()),
                ("request_id", models.TextField()),
                ("memory_id", models.TextField()),
                ("owner_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("operation", models.TextField()),
                ("status", models.TextField()),
                ("scope_digest", models.TextField()),
                ("before_digest", models.TextField(blank=True, null=True)),
                ("after_digest", models.TextField(blank=True, null=True)),
                ("result_version", models.BigIntegerField()),
                ("policy_version", models.TextField()),
                ("gate_results_json", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_memory_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="AiMemoryCommitGuards",
            fields=[
                ("operation_id", models.TextField(primary_key=True, serialize=False)),
                ("audit_present", models.BigIntegerField()),
            ],
            options={
                "db_table": "ai_memory_commit_guards",
            },
        ),
        migrations.CreateModel(
            name="AiMemoryEntries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("kind", models.TextField()),
                ("memory_key", models.TextField()),
                ("memory_key_normalized", models.TextField()),
                ("content", models.TextField()),
                ("content_digest", models.TextField()),
                ("scope_mode", models.TextField()),
                ("scope_json", models.TextField()),
                ("scope_digest", models.TextField()),
                ("status", models.TextField(default="active")),
                ("version", models.BigIntegerField(default=1)),
                ("source", models.TextField()),
                ("source_conversation_id", models.TextField(blank=True, null=True)),
                ("source_message_id", models.TextField(blank=True, null=True)),
                ("last_operation_id", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_memory_entries",
            },
        ),
        migrations.CreateModel(
            name="AiMigrationRun",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("mode", models.CharField(max_length=16)),
                ("status", models.CharField(max_length=32)),
                ("source_path_digest", models.CharField(max_length=64)),
                ("source_snapshot_digest", models.CharField(max_length=64)),
                ("target_snapshot_digest", models.CharField(default="", max_length=64)),
                ("source_counts", models.JSONField(default=dict)),
                ("target_counts", models.JSONField(default=dict)),
                ("approved_run_id", models.CharField(default="", max_length=64)),
                ("consumed_by_run_id", models.CharField(default="", max_length=64)),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ai_migration_runs",
            },
        ),
        migrations.CreateModel(
            name="AiModels",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("version", models.BigIntegerField(default=1)),
                ("name", models.TextField()),
                ("protocol", models.TextField()),
                ("model_type", models.TextField()),
                ("model_name", models.TextField()),
                ("base_url", models.TextField(default="")),
                ("api_key_encrypted", models.TextField(default="")),
                ("api_key_suffix", models.TextField(default="")),
                ("is_default_text_model", models.BigIntegerField(default=0)),
                ("status", models.TextField()),
                ("timeout_ms", models.BigIntegerField(default=60000)),
                ("max_tokens", models.BigIntegerField(default=4096)),
                ("reasoning_mode", models.TextField(default="auto")),
                ("temperature_milli", models.BigIntegerField(default=200)),
                ("max_tool_rounds", models.BigIntegerField(default=6)),
                ("max_total_tool_calls", models.BigIntegerField(default=12)),
                ("last_test_result", models.TextField(blank=True, null=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="AiMutationAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=128)),
                ("actor_email", models.CharField(max_length=320)),
                ("actor_role", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=128)),
                ("scope_digest", models.CharField(max_length=64)),
                ("response_digest", models.CharField(max_length=64)),
                ("revision", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_mutation_audits",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceAdminAudits",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("actor_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("action", models.TextField()),
                ("entity_type", models.TextField()),
                ("entity_id", models.TextField()),
                ("before_json", models.TextField(default="{}")),
                ("after_json", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_admin_audits",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceAssetCleanupQueue",
            fields=[
                ("object_key", models.TextField(primary_key=True, serialize=False)),
                ("attempt_count", models.BigIntegerField(default=0)),
                ("last_error", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_asset_cleanup_queue",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceAssetFavorites",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "asset_id",
                        "actor_email",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_id", models.TextField()),
                ("actor_email", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_asset_favorites",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceAssets",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("scope_json", models.TextField()),
                ("scene", models.TextField()),
                ("object_key", models.TextField()),
                ("content_sha256", models.TextField()),
                ("mime_type", models.TextField()),
                ("byte_size", models.BigIntegerField()),
                ("width", models.BigIntegerField()),
                ("height", models.BigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_assets",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceDispatchReceipts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("item_id", models.TextField()),
                ("job_id", models.TextField()),
                ("owner_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("model_profile_id", models.TextField()),
                ("model_profile_version", models.BigIntegerField()),
                ("model_name", models.TextField()),
                ("scene", models.TextField()),
                ("size", models.TextField()),
                ("prompt_digest", models.TextField()),
                (
                    "dispatched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "ai_space_dispatch_receipts",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceJobItems",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("ordinal", models.BigIntegerField()),
                ("status", models.TextField(default="queued")),
                ("attempt_count", models.BigIntegerField(default=0)),
                ("lease_token", models.TextField(default="")),
                ("lease_epoch", models.BigIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("dispatch_started_at", models.DateTimeField(blank=True, null=True)),
                ("pending_object_key", models.TextField(default="")),
                ("provider_request_id", models.TextField(default="")),
                ("asset_id", models.TextField(blank=True, null=True)),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_job_items",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceJobs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("client_request_id", models.TextField()),
                ("request_digest", models.TextField()),
                ("owner_email", models.TextField()),
                ("scope_json", models.TextField()),
                ("scene", models.TextField()),
                ("template_name", models.TextField()),
                ("template_version", models.BigIntegerField()),
                ("model_profile_name", models.TextField()),
                ("model_profile_version", models.BigIntegerField()),
                ("model_name", models.TextField()),
                ("product_name", models.TextField()),
                ("brand", models.TextField(default="")),
                ("sku", models.TextField(default="")),
                ("selling_points", models.TextField(default="")),
                ("final_prompt", models.TextField()),
                ("prompt_digest", models.TextField()),
                ("size", models.TextField()),
                ("requested_count", models.BigIntegerField()),
                ("succeeded_count", models.BigIntegerField(default=0)),
                ("failed_count", models.BigIntegerField(default=0)),
                ("cancelled_count", models.BigIntegerField(default=0)),
                ("status", models.TextField(default="queued")),
                ("cancel_requested", models.BigIntegerField(default=0)),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_jobs",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceModelProfiles",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("protocol", models.TextField(default="openai_images")),
                ("model_name", models.TextField()),
                ("base_url", models.TextField()),
                ("api_key_encrypted", models.TextField(default="")),
                ("api_key_suffix", models.TextField(default="")),
                ("status", models.TextField(default="enabled")),
                ("version", models.BigIntegerField(default=1)),
                ("timeout_ms", models.BigIntegerField(default=90000)),
                ("last_success_result", models.TextField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_model_profiles",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceSchemaUpgrades",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "ai_space_schema_upgrades",
            },
        ),
        migrations.CreateModel(
            name="AiSpaceTemplates",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("scene", models.TextField()),
                ("name", models.TextField()),
                ("prompt_template", models.TextField()),
                ("size", models.TextField(default="1024x1024")),
                ("version", models.BigIntegerField(default=1)),
                ("is_enabled", models.BigIntegerField(default=1)),
                ("is_default", models.BigIntegerField(default=0)),
                ("updated_by", models.TextField(default="system")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_templates",
            },
        ),
        migrations.CreateModel(
            name="AiSystemSettings",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("value_json", models.TextField()),
                ("updated_by", models.TextField(default="")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_system_settings",
            },
        ),
        migrations.CreateModel(
            name="AiToolAuditLogs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("request_id", models.TextField()),
                ("invocation_id", models.TextField(default="")),
                ("provider_call_id", models.TextField(blank=True, null=True)),
                ("actor_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("surface", models.TextField()),
                ("tool_name", models.TextField()),
                ("arguments_json", models.TextField(default="{}")),
                ("status", models.TextField()),
                ("row_count", models.BigIntegerField(blank=True, null=True)),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("response_digest", models.TextField(blank=True, null=True)),
                ("error_code", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_tool_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="AiWorkflowEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("node_key", models.TextField(blank=True, null=True)),
                ("owner_email", models.TextField()),
                ("actor_email", models.TextField()),
                ("event_type", models.TextField()),
                ("from_status", models.TextField(default="")),
                ("to_status", models.TextField(default="")),
                ("run_version", models.BigIntegerField()),
                ("details_json", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_workflow_events",
            },
        ),
        migrations.CreateModel(
            name="AiWorkflowNodeRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("node_key", models.TextField()),
                ("position", models.BigIntegerField()),
                ("node_type", models.TextField()),
                ("depends_on_json", models.TextField(default="[]")),
                ("instruction", models.TextField()),
                ("input_json", models.TextField(default="{}")),
                ("output_json", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="pending")),
                ("version", models.BigIntegerField(default=1)),
                ("mutation_token", models.TextField(default="")),
                ("reviewer_email", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_workflow_node_runs",
            },
        ),
        migrations.CreateModel(
            name="AiWorkflowRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("client_request_id", models.TextField()),
                ("request_digest", models.TextField()),
                ("scope_json", models.TextField()),
                ("name", models.TextField()),
                ("graph_json", models.TextField()),
                ("graph_digest", models.TextField()),
                ("input_json", models.TextField(default="{}")),
                ("output_json", models.TextField(blank=True, null=True)),
                ("model_id", models.TextField(default="")),
                ("model_version", models.BigIntegerField(default=0)),
                ("allowed_tools_json", models.TextField(default="[]")),
                ("tool_policy_digest", models.TextField(default="")),
                ("provider_round_count", models.BigIntegerField(default=0)),
                ("tool_call_count", models.BigIntegerField(default=0)),
                (
                    "provider_dispatch_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("dry_run", models.BigIntegerField(default=0)),
                ("status", models.TextField(default="queued")),
                ("current_node_key", models.TextField(blank=True, null=True)),
                ("version", models.BigIntegerField(default=1)),
                ("mutation_token", models.TextField(default="")),
                ("cancel_requested", models.BigIntegerField(default=0)),
                ("retryable", models.BigIntegerField(default=0)),
                ("resume_count", models.BigIntegerField(default=0)),
                ("attempt_count", models.BigIntegerField(default=0)),
                ("lease_token", models.TextField(default="")),
                ("lease_epoch", models.BigIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_workflow_runs",
            },
        ),
        migrations.CreateModel(
            name="AiWriteAuthority",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="d1", max_length=16)),
                ("authority_epoch", models.UUIDField(null=True)),
                ("cutover_id", models.CharField(default="", max_length=128)),
                (
                    "migration_verify_run_id",
                    models.CharField(default="", max_length=64),
                ),
                ("activated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ai_write_authority",
            },
        ),
        migrations.CreateModel(
            name="AiWriteReceipt",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("actor_email", models.CharField(max_length=320)),
                ("principal_digest", models.CharField(max_length=64)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=400)),
                ("query_sha256", models.CharField(max_length=64)),
                ("body_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(default="processing", max_length=20)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ai_write_request_receipts",
            },
        ),
        migrations.CreateModel(
            name="AiAgentJobs",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("client_request_id", models.TextField()),
                ("request_digest", models.TextField()),
                ("scope_json", models.TextField()),
                ("task", models.TextField()),
                ("input_json", models.TextField(default="{}")),
                ("state_json", models.TextField(default="{}")),
                ("output_json", models.TextField(blank=True, null=True)),
                ("model_id", models.TextField(default="")),
                ("model_version", models.BigIntegerField(default=0)),
                ("allowed_tools_json", models.TextField(default="[]")),
                ("tool_policy_digest", models.TextField(default="")),
                ("provider_round_count", models.BigIntegerField(default=0)),
                ("tool_call_count", models.BigIntegerField(default=0)),
                (
                    "provider_dispatch_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("status", models.TextField(default="queued")),
                ("phase", models.TextField(default="queued")),
                ("step_index", models.BigIntegerField(default=0)),
                ("version", models.BigIntegerField(default=1)),
                ("mutation_token", models.TextField(default="")),
                ("cancel_requested", models.BigIntegerField(default=0)),
                ("retryable", models.BigIntegerField(default=0)),
                ("resume_count", models.BigIntegerField(default=0)),
                ("attempt_count", models.BigIntegerField(default=0)),
                ("lease_token", models.TextField(default="")),
                ("lease_epoch", models.BigIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("workflow_run_id", models.TextField(blank=True, null=True)),
                ("workflow_node_key", models.TextField(blank=True, null=True)),
                ("error_code", models.TextField(default="")),
                ("error_message", models.TextField(default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_agent_jobs",
                "indexes": [
                    models.Index(
                        fields=["status", "next_run_at", "created_at", "id"],
                        name="ai_832f9ca5787d58451dba",
                    ),
                    models.Index(
                        fields=["owner_email", "created_at", "id"],
                        name="ai_2902eda62ab3a5642817",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_email", "client_request_id"),
                        name="ai_949435c0734d90375ed1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "queued",
                                    "running",
                                    "paused",
                                    "completed",
                                    "failed",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="ai_ck_dddef78d566cfc92a595",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "phase__in",
                                [
                                    "queued",
                                    "executing",
                                    "paused",
                                    "completed",
                                    "failed",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="ai_ck_89ff4fbd2a24f5ee78ce",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cancel_requested__in", [0, 1])),
                        name="ai_ck_e8dd8f0615aa2983bdca",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retryable__in", [0, 1])),
                        name="ai_ck_3f27daee6ac08c5f22ae",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("step_index__gte", 0), ("step_index__lte", 64)
                        ),
                        name="ai_ck_d77cf2d3862933e1a271",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resume_count__gte", 0), ("resume_count__lte", 16)
                        ),
                        name="ai_ck_cb152d9e89ff4675e004",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("model_version__gte", 0)),
                        name="ai_ck_d5135560631fb5d41c3d",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_round_count__gte", 0)),
                        name="ai_ck_0fd49976566c02854412",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tool_call_count__gte", 0)),
                        name="ai_ck_1c0a1d7a33bb08106c1e",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="ai_ck_9f26b73d57c765d5877d",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)),
                        name="ai_ck_fd7799247044ddbf3103",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lease_epoch__gte", 0)),
                        name="ai_ck_1d8cc6509515e484ab7c",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AiAgentEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("actor_email", models.TextField()),
                ("event_type", models.TextField()),
                ("from_status", models.TextField(default="")),
                ("to_status", models.TextField(default="")),
                ("job_version", models.BigIntegerField()),
                ("details_json", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistant.aiagentjobs",
                    ),
                ),
            ],
            options={
                "db_table": "ai_agent_events",
            },
        ),
        migrations.CreateModel(
            name="AiAgentCheckpoints",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("ordinal", models.BigIntegerField()),
                ("kind", models.TextField()),
                ("state_json", models.TextField(default="{}")),
                ("output_digest", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistant.aiagentjobs",
                    ),
                ),
            ],
            options={
                "db_table": "ai_agent_checkpoints",
            },
        ),
        migrations.CreateModel(
            name="AiAgentProviderResults",
            fields=[
                (
                    "dispatch",
                    models.OneToOneField(
                        db_column="dispatch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="ai_assistant.aiagentproviderdispatches",
                    ),
                ),
                ("response_json", models.TextField()),
                ("response_digest", models.TextField()),
                ("usage_json", models.TextField(default="{}")),
                ("provider_request_id", models.TextField(default="")),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "ai_agent_provider_results",
            },
        ),
        migrations.AddField(
            model_name="aiagentproviderdispatches",
            name="job",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aiagentjobs",
            ),
        ),
        migrations.CreateModel(
            name="AiAgentToolResults",
            fields=[
                (
                    "tool_dispatch",
                    models.OneToOneField(
                        db_column="tool_dispatch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="ai_assistant.aiagenttooldispatches",
                    ),
                ),
                ("result_json", models.TextField()),
                ("result_digest", models.TextField()),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "ai_agent_tool_results",
            },
        ),
        migrations.AddField(
            model_name="aiagenttooldispatches",
            name="job",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aiagentjobs",
            ),
        ),
        migrations.AddField(
            model_name="aiagenttooldispatches",
            name="provider_dispatch",
            field=models.ForeignKey(
                db_column="provider_dispatch_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aiagentproviderdispatches",
            ),
        ),
        migrations.CreateModel(
            name="AiAnalysisRuns",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("scope_json", models.TextField()),
                ("dataset", models.TextField()),
                ("query_digest", models.TextField()),
                ("plan_digest", models.TextField()),
                ("operations_json", models.TextField()),
                ("data_cutoff_date", models.TextField(blank=True, null=True)),
                ("source_rows", models.BigIntegerField()),
                ("returned_rows", models.BigIntegerField()),
                ("truncated", models.BigIntegerField(default=0)),
                ("result_digest", models.TextField()),
                ("request_id", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_analysis_runs",
                "indexes": [
                    models.Index(
                        fields=["dataset", "created_at", "id"],
                        name="ai_e48da48139ae1b114e2b",
                    ),
                    models.Index(
                        fields=["owner_email", "created_at", "id"],
                        name="ai_e7dc0021f900936d6fbf",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "actor_role__in",
                                ["viewer", "analyst", "operator", "admin"],
                            )
                        ),
                        name="ai_ck_9a3acbd16c6cd80d6084",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "dataset__in",
                                [
                                    "sales_category",
                                    "netshop_product_daily",
                                    "netshop_promotion",
                                ],
                            )
                        ),
                        name="ai_ck_7729a062eb61d17420d8",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("truncated__in", [0, 1])),
                        name="ai_ck_07f0097472e56ce04171",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_rows__gte", 0)),
                        name="ai_ck_2c3bfc3083e6e13caa27",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("returned_rows__gte", 0)),
                        name="ai_ck_705d545bbea302999855",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AiArtifactDeliveries",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("artifact_id", models.TextField()),
                ("request_id", models.TextField()),
                ("actor_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("surface", models.TextField()),
                ("status", models.TextField()),
                ("byte_size", models.BigIntegerField(blank=True, null=True)),
                ("content_digest", models.TextField(blank=True, null=True)),
                ("error_code", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_artifact_deliveries",
                "indexes": [
                    models.Index(
                        fields=["artifact_id", "created_at"],
                        name="ai_4d064cc0c307921427a9",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["succeeded", "failed"])),
                        name="ai_ck_292fe0645a24258c8051",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiArtifacts",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("conversation_id", models.TextField()),
                ("message_id", models.TextField()),
                ("owner_email", models.TextField()),
                ("kind", models.TextField()),
                ("title", models.TextField()),
                ("file_name", models.TextField()),
                ("mime_type", models.TextField()),
                ("source_tool", models.TextField()),
                ("columns_json", models.TextField(default="[]")),
                ("rows_json", models.TextField(default="[]")),
                ("row_count", models.BigIntegerField(default=0)),
                ("truncated", models.BigIntegerField(default=0)),
                ("content_digest", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_artifacts",
                "indexes": [
                    models.Index(
                        fields=["owner_email", "created_at"],
                        name="ai_f9d709e901e32b06fb74",
                    ),
                    models.Index(
                        fields=["conversation_id", "message_id", "created_at"],
                        name="ai_2c8082ddc0f4671a40a3",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["table"])),
                        name="ai_ck_e716b8f3893b48e02faf",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiChannelCallbackEvents",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("channel_id", models.TextField()),
                ("event_key", models.TextField()),
                ("payload_digest", models.TextField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "ai_channel_callback_events",
                "indexes": [
                    models.Index(
                        fields=["channel_id", "received_at"],
                        name="ai_4485f5e6831a6f4db86c",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel_id", "event_key"),
                        name="ai_f1d89fcaec213cc6b34f",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiChannels",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("kind", models.TextField()),
                ("status", models.TextField()),
                ("send_enabled", models.BigIntegerField(default=0)),
                ("callback_enabled", models.BigIntegerField(default=0)),
                ("webhook_url", models.TextField(default="")),
                ("callback_token_encrypted", models.TextField(default="")),
                ("callback_token_suffix", models.TextField(default="")),
                ("aes_key_encrypted", models.TextField(default="")),
                ("aes_key_suffix", models.TextField(default="")),
                ("receiver_id", models.TextField(default="")),
                ("last_test_result", models.TextField(blank=True, null=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_channels",
                "indexes": [
                    models.Index(
                        fields=["status", "kind", "updated_at"],
                        name="ai_1b4e9210a424d924ad01",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "dingtalk_group_bot",
                                    "dingtalk_app",
                                    "wechat_work_group_bot",
                                    "wechat_work_app",
                                ],
                            )
                        ),
                        name="ai_ck_771f01e9ac2239f25848",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["enabled", "disabled"])),
                        name="ai_ck_7209d1f7a80cc96461fc",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AiChatProviderDispatches",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("owner_email", models.TextField()),
                ("model_id", models.TextField()),
                ("dispatch_ordinal", models.BigIntegerField()),
                ("reserved_at", models.DateTimeField()),
                ("provider_called_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        db_column="receipt_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_assistant.aichatrequestreceipts",
                    ),
                ),
            ],
            options={
                "db_table": "ai_chat_provider_dispatches",
            },
        ),
        migrations.CreateModel(
            name="AiConversationDeletionAudits",
            fields=[
                ("audit_id", models.TextField(primary_key=True, serialize=False)),
                ("conversation_id", models.TextField()),
                ("conversation_owner", models.TextField()),
                ("actor_email", models.TextField()),
                ("actor_role", models.TextField()),
                ("reason", models.TextField()),
                ("deleted_message_count", models.BigIntegerField(default=0)),
                ("deleted_artifact_count", models.BigIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_conversation_deletion_audits",
                "indexes": [
                    models.Index(
                        fields=["actor_email", "deleted_at"],
                        name="ai_600b19f054b906ff74d2",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation_id",), name="ai_65fb2cfee7b65d4e55d1"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "actor_role__in",
                                ["viewer", "analyst", "operator", "admin"],
                            )
                        ),
                        name="ai_ck_f20c7b68ce3c252dd94e",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AiConversationMessages",
            fields=[
                ("ordinal", models.PositiveBigIntegerField(db_index=True, default=0)),
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("conversation_id", models.TextField()),
                ("role", models.TextField()),
                ("content", models.TextField()),
                ("message_kind", models.TextField(default="message")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_conversation_messages",
                "indexes": [
                    models.Index(
                        fields=["conversation_id", "message_kind", "created_at"],
                        name="ai_c52fee85d06a5f4a1543",
                    ),
                    models.Index(
                        fields=["conversation_id", "created_at"],
                        name="ai_701838ab3eade5e8d9e8",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["user", "assistant"])),
                        name="ai_ck_7c55c35874eb9f23870a",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiConversationScopes",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        db_column="conversation_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ai_assistant.aiconversations",
                    ),
                ),
                ("scope_json", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_conversation_scopes",
            },
        ),
        migrations.AddIndex(
            model_name="aiconversations",
            index=models.Index(
                fields=["updated_at", "id"], name="ai_56a5a65c0a8e0cdee639"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversations",
            index=models.Index(
                fields=["created_by", "updated_at"], name="ai_1eb6c53b52c522d7a849"
            ),
        ),
        migrations.AddField(
            model_name="aichatrequestreceipts",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                db_column="conversation_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistant.aiconversations",
            ),
        ),
        migrations.AddIndex(
            model_name="aiknowledgeentries",
            index=models.Index(
                fields=["status", "source_type", "updated_at"],
                name="ai_30894b9105c2fa28fc72",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiknowledgeentries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        ["system_policy", "business_metric", "identity_mapping"],
                    )
                ),
                name="ai_ck_fba54d498c8affb612f4",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiknowledgeentries",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "disabled"])),
                name="ai_ck_b08cf6906f8cced4279d",
            ),
        ),
        migrations.AddIndex(
            model_name="aimemoryauditlogs",
            index=models.Index(
                fields=["memory_id", "created_at", "id"], name="ai_6e705ac068ce94cf7d41"
            ),
        ),
        migrations.AddIndex(
            model_name="aimemoryauditlogs",
            index=models.Index(
                fields=["owner_email", "created_at", "id"],
                name="ai_768eb206f958518006af",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryauditlogs",
            constraint=models.UniqueConstraint(
                fields=("operation_id",), name="ai_6d46a8bbeb6813cce843"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryauditlogs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor_role__in", ["viewer", "analyst", "operator", "admin"])
                ),
                name="ai_ck_bd834f538f3a16733bd7",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryauditlogs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operation__in", ["create", "update", "archive", "duplicate"])
                ),
                name="ai_ck_8a3a3f6b0e4e94f4edf0",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryauditlogs",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["succeeded", "duplicate"])),
                name="ai_ck_a400895d04c914f80c38",
            ),
        ),
        migrations.AddIndex(
            model_name="aimemoryentries",
            index=models.Index(
                fields=["owner_email", "status", "updated_at", "id"],
                name="ai_3263a71d156dd29d4118",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryentries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("owner_email", "kind", "memory_key_normalized", "scope_digest"),
                name="ai_memory_active_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryentries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["preference", "glossary", "business_context"])
                ),
                name="ai_ck_5a7b4825a9064ca4d0c4",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryentries",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_mode__in", ["owner", "data_scope"])),
                name="ai_ck_f36c7ca8be8e1c7b5f32",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryentries",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])),
                name="ai_ck_9e9c31b8850e5f5ccad0",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimemoryentries",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["management_ui", "web_chat"])),
                name="ai_ck_6e7dafcb9fa4c3c38b3b",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodels",
            index=models.Index(
                fields=["status", "model_type", "updated_at"],
                name="ai_4d0474015dbc6ea22e8f",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodels",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_default_text_model", 1),
                    ("model_type", "text"),
                    ("status", "enabled"),
                ),
                fields=("is_default_text_model",),
                name="ai_default_text_model_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodels",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protocol__in", ["openai_compatible", "anthropic"])
                ),
                name="ai_ck_f0310d6adef4714c9992",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodels",
            constraint=models.CheckConstraint(
                condition=models.Q(("model_type__in", ["text", "image", "vision"])),
                name="ai_ck_e987526c81400be83cb4",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodels",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["enabled", "disabled"])),
                name="ai_ck_42a2926c10e651aa60cb",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodels",
            constraint=models.CheckConstraint(
                condition=models.Q(("reasoning_mode__in", ["auto", "disabled"])),
                name="ai_ck_92aaec6dbb8f9b7fcfed",
            ),
        ),
        migrations.AddIndex(
            model_name="aispaceadminaudits",
            index=models.Index(
                fields=["entity_type", "entity_id", "created_at", "id"],
                name="ai_3444e2ca9271dcc340a7",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispaceadminaudits",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "upsert_profile",
                            "delete_profile",
                            "upsert_template",
                            "delete_template",
                        ],
                    )
                ),
                name="ai_ck_911a3d907511be0a1229",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispaceadminaudits",
            constraint=models.CheckConstraint(
                condition=models.Q(("entity_type__in", ["model_profile", "template"])),
                name="ai_ck_bdace58f4c3f62b0ff58",
            ),
        ),
        migrations.AddIndex(
            model_name="aispaceassetfavorites",
            index=models.Index(
                fields=["actor_email", "created_at", "asset_id"],
                name="ai_976edc3d933aaab70dc5",
            ),
        ),
        migrations.CreateModel(
            name="AiSpaceDispatchResults",
            fields=[
                (
                    "dispatch",
                    models.OneToOneField(
                        db_column="dispatch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ai_assistant.aispacedispatchreceipts",
                    ),
                ),
                ("status", models.TextField()),
                ("provider_request_id", models.TextField(default="")),
                ("error_code", models.TextField(default="")),
                ("usage_json", models.TextField(default="{}")),
                ("estimated_cost_cents", models.BigIntegerField(blank=True, null=True)),
                ("price_version", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_space_dispatch_results",
            },
        ),
        migrations.AddIndex(
            model_name="aispacedispatchreceipts",
            index=models.Index(
                fields=["model_profile_id", "dispatched_at", "id"],
                name="ai_c73a5d344ef51ebae249",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacedispatchreceipts",
            index=models.Index(
                fields=["owner_email", "dispatched_at", "id"],
                name="ai_892be7fe1ba44feef138",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacedispatchreceipts",
            constraint=models.UniqueConstraint(
                fields=("item_id",), name="ai_e26766e9529859782ab9"
            ),
        ),
        migrations.AddField(
            model_name="aispaceassets",
            name="item",
            field=models.ForeignKey(
                db_column="item_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_assistant.aispacejobitems",
            ),
        ),
        migrations.AddField(
            model_name="aispacejobitems",
            name="job",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_assistant.aispacejobs",
            ),
        ),
        migrations.AddField(
            model_name="aispaceassets",
            name="job",
            field=models.ForeignKey(
                db_column="job_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_assistant.aispacejobs",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacemodelprofiles",
            index=models.Index(
                fields=["status", "updated_at", "id"], name="ai_1eee8d0d97796f513144"
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacemodelprofiles",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["enabled", "disabled"])),
                name="ai_ck_13bf89e36f2dfd4b45a5",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacemodelprofiles",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("timeout_ms__gte", 3000), ("timeout_ms__lte", 120000)
                ),
                name="ai_ck_f8acd5f4279b05c419a7",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacemodelprofiles",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ai_ck_74314af32937a1df5aee",
            ),
        ),
        migrations.AddField(
            model_name="aispacejobs",
            name="model_profile",
            field=models.ForeignKey(
                db_column="model_profile_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aispacemodelprofiles",
            ),
        ),
        migrations.AddField(
            model_name="aispacetemplates",
            name="model_profile",
            field=models.ForeignKey(
                blank=True,
                db_column="model_profile_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aispacemodelprofiles",
            ),
        ),
        migrations.AddField(
            model_name="aispacejobs",
            name="template",
            field=models.ForeignKey(
                db_column="template_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="ai_assistant.aispacetemplates",
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolauditlogs",
            index=models.Index(
                fields=["invocation_id", "created_at"], name="ai_7daace5654b492099a5f"
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolauditlogs",
            index=models.Index(
                fields=["tool_name", "created_at"], name="ai_62424d80205d6d452006"
            ),
        ),
        migrations.AddIndex(
            model_name="aitoolauditlogs",
            index=models.Index(
                fields=["actor_email", "created_at"], name="ai_1ca4f2459a1422c597be"
            ),
        ),
        migrations.AddField(
            model_name="aiworkflownoderuns",
            name="agent_job",
            field=models.ForeignKey(
                blank=True,
                db_column="agent_job_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_assistant.aiagentjobs",
            ),
        ),
        migrations.AddIndex(
            model_name="aiworkflowruns",
            index=models.Index(
                fields=["status", "next_run_at", "created_at", "id"],
                name="ai_b03812a90d7ef2d47569",
            ),
        ),
        migrations.AddIndex(
            model_name="aiworkflowruns",
            index=models.Index(
                fields=["owner_email", "created_at", "id"],
                name="ai_a393e7db5349bfde139e",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.UniqueConstraint(
                fields=("owner_email", "client_request_id"),
                name="ai_ca04cddd5d43550fc394",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("dry_run__in", [0, 1])),
                name="ai_ck_b62d38b9d3cfbfaf4ce9",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "queued",
                            "running",
                            "waiting_review",
                            "paused",
                            "completed",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="ai_ck_88d5c09e66ffd44225ce",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("cancel_requested__in", [0, 1])),
                name="ai_ck_8340259e51187630a73d",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("retryable__in", [0, 1])),
                name="ai_ck_d3ba55ff2c6c3b81fd6d",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("resume_count__gte", 0), ("resume_count__lte", 16)),
                name="ai_ck_883053802866b5e1af6c",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("model_version__gte", 0)),
                name="ai_ck_f42ef7e78ad259514e1c",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_round_count__gte", 0)),
                name="ai_ck_b629a8f2bb81e4ea0062",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("tool_call_count__gte", 0)),
                name="ai_ck_9f27c7d6abd612f30219",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ai_ck_7afef6cb6e4a100ea9d4",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="ai_ck_321e47d03f02b0bb6c74",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowruns",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_epoch__gte", 0)),
                name="ai_ck_41c8f4141e4d03cf1568",
            ),
        ),
        migrations.AddField(
            model_name="aiworkflownoderuns",
            name="run",
            field=models.ForeignKey(
                db_column="run_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_assistant.aiworkflowruns",
            ),
        ),
        migrations.AddField(
            model_name="aiworkflowevents",
            name="run",
            field=models.ForeignKey(
                db_column="run_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_assistant.aiworkflowruns",
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentevents",
            index=models.Index(
                fields=["job", "created_at", "id"], name="ai_ab857d760133f6613547"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentevents",
            constraint=models.CheckConstraint(
                condition=models.Q(("job_version__gte", 1)),
                name="ai_ck_dfd3af69a1236c401fd3",
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentcheckpoints",
            index=models.Index(
                fields=["job", "ordinal"], name="ai_c7b0f32499801f5805ef"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentcheckpoints",
            constraint=models.UniqueConstraint(
                fields=("job", "ordinal"), name="ai_ae84949490ac546dfd82"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentcheckpoints",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["checkpoint", "completed", "paused", "failed"])
                ),
                name="ai_ck_b4672b98eb5d3441036d",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentcheckpoints",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gte", 1), ("ordinal__lte", 64)),
                name="ai_ck_12d449714a9f44253d07",
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentproviderdispatches",
            index=models.Index(
                fields=["state", "reserved_at"], name="ai_883deb0333ada132ceaf"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentproviderdispatches",
            index=models.Index(
                fields=["model_id", "reserved_at"], name="ai_cfacc1afa216635b87b1"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentproviderdispatches",
            index=models.Index(
                fields=["owner_email", "reserved_at"], name="ai_22cc5d4f884b3b234360"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.UniqueConstraint(
                fields=("job", "dispatch_ordinal"), name="ai_af5a51f7d17b4eb8cba3"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor_role__in", ["analyst", "operator", "admin"])
                ),
                name="ai_ck_8a931038bce003e47c7e",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["calling", "succeeded", "failed", "unknown"])
                ),
                name="ai_ck_e3f40a8b4fec7b578deb",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dispatch_ordinal__gte", 1), ("dispatch_ordinal__lte", 20)
                ),
                name="ai_ck_8c81787b1d253d47c20a",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(("model_version__gte", 1)),
                name="ai_ck_b3d1ea6b36bc7f0c1747",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagentproviderdispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_epoch__gte", 1)),
                name="ai_ck_ece78fdd86640bd40d35",
            ),
        ),
        migrations.AddIndex(
            model_name="aiagenttooldispatches",
            index=models.Index(
                fields=["job", "state", "tool_call_ordinal"],
                name="ai_a3878f6f2fea46297124",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagenttooldispatches",
            constraint=models.UniqueConstraint(
                fields=("provider_dispatch", "provider_call_id"),
                name="ai_035bc417890ef5bc232c",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagenttooldispatches",
            constraint=models.UniqueConstraint(
                fields=("job", "tool_call_ordinal"), name="ai_0a721ad37ed1dedda213"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagenttooldispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["calling", "succeeded", "failed", "unknown"])
                ),
                name="ai_ck_fd6b2e24d641bfb04994",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagenttooldispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tool_call_ordinal__gte", 1), ("tool_call_ordinal__lte", 40)
                ),
                name="ai_ck_2f947338251f85c2774b",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiagenttooldispatches",
            constraint=models.CheckConstraint(
                condition=models.Q(("lease_epoch__gte", 1)),
                name="ai_ck_550b5a2f8c305f1463b6",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatproviderdispatches",
            index=models.Index(fields=["reserved_at"], name="ai_786cb67466d1ee4f5ec4"),
        ),
        migrations.AddIndex(
            model_name="aichatproviderdispatches",
            index=models.Index(
                fields=["model_id", "reserved_at"], name="ai_70a8c2b8996308acf5fd"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatproviderdispatches",
            index=models.Index(
                fields=["owner_email", "reserved_at"], name="ai_3cbdee118d38052410ef"
            ),
        ),
        migrations.AddConstraint(
            model_name="aichatproviderdispatches",
            constraint=models.UniqueConstraint(
                fields=("receipt", "dispatch_ordinal"), name="ai_0cbc96dfc391e4c17f1d"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversationscopes",
            index=models.Index(
                fields=["scope_json", "created_at"], name="ai_fb73bbf3175be34cc564"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["status", "model_id", "admitted_at"],
                name="ai_e22bf0e1d0d6ac1ced76",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["status", "admitted_at"], name="ai_a8db3a812b462c2ab56f"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["owner_email", "admitted_at"], name="ai_e37717437f2b69490aa2"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["status", "owner_email", "model_id", "provider_started_at"],
                name="ai_5a97610ffa86c2ca2004",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["model_id", "provider_started_at"],
                name="ai_3ce5b3a295708160d5f0",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["owner_email", "provider_started_at"],
                name="ai_32945e7100cc7a4879cf",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["provider_started_at"], name="ai_c4fb16e23190cbbbe95c"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["conversation", "created_at"], name="ai_155a371b6c235aebb317"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatrequestreceipts",
            index=models.Index(
                fields=["status", "updated_at"], name="ai_c8d4ceeb25be876c219a"
            ),
        ),
        migrations.AddConstraint(
            model_name="aichatrequestreceipts",
            constraint=models.UniqueConstraint(
                fields=("owner_email", "client_request_id"),
                name="ai_a8ab4d361788c28e79d6",
            ),
        ),
        migrations.AddConstraint(
            model_name="aichatrequestreceipts",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["processing", "dispatched", "succeeded", "failed", "unknown"],
                    )
                ),
                name="ai_ck_20e4b872ffe66952794a",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacedispatchresults",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["succeeded", "failed"])),
                name="ai_ck_a98b5a2e9f5a8817e4e6",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacejobitems",
            index=models.Index(
                fields=["job", "ordinal"], name="ai_7c128b02f4c486c7369a"
            ),
        ),
        migrations.AddIndex(
            model_name="aispacejobitems",
            index=models.Index(
                fields=["status", "created_at", "job", "ordinal"],
                name="ai_663582f63f22ada00455",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobitems",
            constraint=models.UniqueConstraint(
                fields=("job", "ordinal"), name="ai_37c21e14159df90cecc0"
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobitems",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "succeeded", "failed", "cancelled"],
                    )
                ),
                name="ai_ck_f08ebc8d0f85c09433ed",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobitems",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gte", 1), ("ordinal__lte", 4)),
                name="ai_ck_c8add7794011a23a88e4",
            ),
        ),
        migrations.AddIndex(
            model_name="aispaceassets",
            index=models.Index(
                fields=["job", "created_at", "id"], name="ai_190b5234d99baa7c3b03"
            ),
        ),
        migrations.AddIndex(
            model_name="aispaceassets",
            index=models.Index(
                fields=["owner_email", "created_at", "id"],
                name="ai_705bbfa0ae4ba8fe4734",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispaceassets",
            constraint=models.UniqueConstraint(
                fields=("object_key",), name="ai_4ca1948508ae478bc4f7"
            ),
        ),
        migrations.AddConstraint(
            model_name="aispaceassets",
            constraint=models.UniqueConstraint(
                fields=("item",), name="ai_43dd6ce03454d3ba9475"
            ),
        ),
        migrations.AddConstraint(
            model_name="aispaceassets",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mime_type__in", ["image/png", "image/jpeg", "image/webp"])
                ),
                name="ai_ck_b816c0c93c29a189d035",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacetemplates",
            index=models.Index(
                fields=["scene", "is_enabled", "is_default", "updated_at", "id"],
                name="ai_5bdb0f0461697a1852f2",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", 1), ("is_enabled", 1)),
                fields=("scene",),
                name="ai_space_default_scene_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scene__in", ["product_main", "product_detail", "promotion"])
                ),
                name="ai_ck_ce115ebcf2e3105df0ef",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("size__in", ["1024x1024", "1024x1536", "1536x1024"])
                ),
                name="ai_ck_2abcec39977e40803a41",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_enabled__in", [0, 1])),
                name="ai_ck_591d3946985e5edd2c37",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_default__in", [0, 1])),
                name="ai_ck_45aeaede187242685d54",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacetemplates",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ai_ck_d36cc35cfdebafb7a960",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacejobs",
            index=models.Index(
                fields=["status", "cancel_requested", "created_at", "id"],
                name="ai_0eeb328373e4ced85f05",
            ),
        ),
        migrations.AddIndex(
            model_name="aispacejobs",
            index=models.Index(
                fields=["owner_email", "created_at", "id"],
                name="ai_fe03299350705be7b14e",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.UniqueConstraint(
                fields=("owner_email", "client_request_id"),
                name="ai_7bc011f5b26cafe6b08a",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scene__in", ["product_main", "product_detail", "promotion"])
                ),
                name="ai_ck_f24492b337288a462d74",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("size__in", ["1024x1024", "1024x1536", "1536x1024"])
                ),
                name="ai_ck_601b389c90c4c8770fe8",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "queued",
                            "running",
                            "succeeded",
                            "partial",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="ai_ck_120ddac759ce1c0051ce",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.CheckConstraint(
                condition=models.Q(("cancel_requested__in", [0, 1])),
                name="ai_ck_62869cd64e221ffe9a7b",
            ),
        ),
        migrations.AddConstraint(
            model_name="aispacejobs",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_count__gte", 1), ("requested_count__lte", 4)
                ),
                name="ai_ck_e4c35b366c33b6a0e8d3",
            ),
        ),
        migrations.AddIndex(
            model_name="aiworkflownoderuns",
            index=models.Index(
                fields=["run", "position", "status"], name="ai_075dae45bd2e75bba604"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.UniqueConstraint(
                fields=("run", "position"), name="ai_5b3c0dc89ee139c59645"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.UniqueConstraint(
                fields=("run", "node_key"), name="ai_f4766765b67496b98409"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.CheckConstraint(
                condition=models.Q(("node_type__in", ["agent", "human_review"])),
                name="ai_ck_08759a66b58691b2aab9",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "running",
                            "waiting_review",
                            "completed",
                            "rejected",
                            "skipped",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="ai_ck_8f872e249ae8ad4d2f88",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0), ("position__lte", 23)),
                name="ai_ck_57d8bdb1f04bd79f5c0b",
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflownoderuns",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ai_ck_98d2fbd72e8dce677366",
            ),
        ),
        migrations.AddIndex(
            model_name="aiworkflowevents",
            index=models.Index(
                fields=["run", "created_at", "id"], name="ai_161bd273c54289370bc4"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiworkflowevents",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_version__gte", 1)),
                name="ai_ck_b031db0045c71aaf0523",
            ),
        ),
    ]
