# Generated by Django 5.2.17 on 2026-09-09 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""CREATE TRIGGER ai_write_fence BEFORE INSERT OR UPDATE OR DELETE
            ON ai_conversation_workspaces FOR EACH ROW EXECUTE FUNCTION ai_runtime_write_fence()""")
        cursor.execute("""CREATE TRIGGER ai_immutable_identity BEFORE UPDATE
            ON ai_conversation_workspaces FOR EACH ROW
            EXECUTE FUNCTION ai_immutable_record_guard('conversation_id', 'module_key')""")
        cursor.execute("""ALTER TABLE ai_conversation_workspaces ADD CONSTRAINT ai_workspace_context_size
            CHECK (octet_length(page_context_json) <= 16000)""")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_postgres_image_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversationWorkspace',
            fields=[
                ('conversation', models.OneToOneField(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workspace', serialize=False, to='ai_assistant.aiconversations')),
                ('module_key', models.TextField()),
                ('page_context_json', models.TextField(default='null')),
                ('last_opened_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_conversation_workspaces',
                'indexes': [models.Index(fields=['module_key', 'last_opened_at'], name='ai_workspace_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(('module_key__in', ['n8n_workflows', 'dashboard', 'shop', 'market', 'customer_service', 'sales', 'inventory', 'product', 'workflow', 'import', 'settings', 'ai'])), name='ai_workspace_module')],
            },
        ),
        migrations.RunPython(install),
    ]
