# Generated by Django 5.2.17 on 2026-09-09 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("ai_dingtalk_sessions", "ai_dingtalk_receipts"):
            cursor.execute(f"CREATE TRIGGER ai_write_fence BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ai_runtime_write_fence()")
        cursor.execute("""CREATE TRIGGER ai_immutable_identity BEFORE UPDATE ON ai_dingtalk_sessions
            FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard('id','config_digest','corp_id','robot_code','sender_id','conversation_type','external_conversation_id','owner_email','scope_json','created_at')""")
        cursor.execute("""CREATE TRIGGER ai_immutable_identity BEFORE UPDATE ON ai_dingtalk_receipts
            FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard('id','session_id','payload_digest','created_at')""")
        cursor.execute("""ALTER TABLE ai_dingtalk_sessions ADD CONSTRAINT ai_ding_scope_size CHECK (octet_length(scope_json)<=16000)""")
        cursor.execute("""ALTER TABLE ai_dingtalk_receipts ADD CONSTRAINT ai_ding_content_size CHECK (octet_length(prompt)<=16000 AND octet_length(reply)<=16000)""")
        cursor.execute("""CREATE FUNCTION ai_dingtalk_conversation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
              IF OLD.conversation_id IS NOT NULL AND NEW.conversation_id IS DISTINCT FROM OLD.conversation_id THEN
                RAISE EXCEPTION 'immutable dingtalk conversation';
              END IF;
              RETURN NEW;
            END $$""")
        cursor.execute("""CREATE TRIGGER ai_ding_conversation_guard BEFORE UPDATE ON ai_dingtalk_sessions
            FOR EACH ROW EXECUTE FUNCTION ai_dingtalk_conversation_guard()""")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_conversation_workspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDingTalkSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('config_digest', models.CharField(max_length=64)),
                ('corp_id', models.CharField(max_length=160)),
                ('robot_code', models.CharField(max_length=160)),
                ('sender_id', models.CharField(max_length=160)),
                ('conversation_type', models.CharField(max_length=1)),
                ('external_conversation_id', models.CharField(max_length=256)),
                ('owner_email', models.CharField(max_length=320)),
                ('scope_json', models.TextField(default='null')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dingtalk_session', to='ai_assistant.aiconversations')),
            ],
            options={
                'db_table': 'ai_dingtalk_sessions',
            },
        ),
        migrations.CreateModel(
            name='AiDingTalkReceipt',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload_digest', models.CharField(max_length=64)),
                ('prompt', models.TextField()),
                ('reply', models.TextField(default='')),
                ('status', models.CharField(default='queued', max_length=16)),
                ('ack_status', models.CharField(default='pending', max_length=16)),
                ('error_code', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.aidingtalksession')),
            ],
            options={
                'db_table': 'ai_dingtalk_receipts',
            },
        ),
        migrations.AddConstraint(
            model_name='aidingtalksession',
            constraint=models.CheckConstraint(condition=models.Q(('conversation_type__in', ['1', '2'])), name='ai_ding_session_type'),
        ),
        migrations.AddIndex(
            model_name='aidingtalkreceipt',
            index=models.Index(fields=['status', 'created_at'], name='ai_ding_queue'),
        ),
        migrations.AddIndex(
            model_name='aidingtalkreceipt',
            index=models.Index(fields=['session', 'status'], name='ai_ding_session_queue'),
        ),
        migrations.AddConstraint(
            model_name='aidingtalkreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'ready', 'sending', 'sent', 'unknown', 'denied', 'failed'])), name='ai_ding_receipt_status'),
        ),
        migrations.AddConstraint(
            model_name='aidingtalkreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('ack_status__in', ['pending', 'sending', 'sent', 'unknown'])), name='ai_ding_ack_status'),
        ),
        migrations.RunPython(install),
    ]
