# Generated by Django 5.2.17 on 2026-09-10 06:01

import django.utils.timezone
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE TRIGGER ai_write_fence BEFORE INSERT OR UPDATE OR DELETE ON ai_dingtalk_settings FOR EACH ROW EXECUTE FUNCTION ai_runtime_write_fence()")
        cursor.execute("CREATE TRIGGER ai_immutable_identity BEFORE UPDATE ON ai_dingtalk_settings FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard('id','identity_json')")
        cursor.execute("ALTER TABLE ai_dingtalk_settings ADD CONSTRAINT ai_ding_settings_size CHECK (octet_length(identity_json)<=4096 AND octet_length(groups_json)<=49152)")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_dingtalk_readonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDingTalkSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('identity_json', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('groups_json', models.TextField(default='[]')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(max_length=320)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_dingtalk_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ai_ding_settings_singleton'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ai_ding_settings_version')],
            },
        ),
        migrations.RunPython(install),
    ]
