# Generated by Django 5.2.17 on 2026-09-10 10:14

from django.db import migrations, models


def constraints(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE ai_models ADD CONSTRAINT ai_generation_options_bound CHECK (octet_length(generation_options_json)<=65536 AND jsonb_typeof(generation_options_json::jsonb)='object')")
            cursor.execute("ALTER TABLE ai_conversation_messages ADD CONSTRAINT ai_execution_bound CHECK (octet_length(execution_json)<=16384 AND jsonb_typeof(execution_json::jsonb)='object')")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_dingtalk_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationmessages',
            name='execution_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='aimodels',
            name='generation_options_json',
            field=models.TextField(default='{}'),
        ),
        migrations.RunPython(constraints),
    ]
