# Generated by Django 5.2.17 on 2026-09-13 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    tables = {"ai_library_revisions": "octet_length(config_json)<=131072 AND version>=1", "ai_execution_guidance": "octet_length(snapshot_json)<=65536", "ai_report_runs": "octet_length(snapshot_json)<=32768", "ai_report_deliveries": "status IN ('reserved','sent','unknown')"}
    with schema_editor.connection.cursor() as cursor:
        for table, bound in tables.items():
            cursor.execute(f"CREATE TRIGGER ai_write_fence BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ai_runtime_write_fence()")
            if table != "ai_report_deliveries":
                cursor.execute(f"CREATE TRIGGER ai_immutable_evidence BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard()")
            cursor.execute(f"ALTER TABLE {table} ADD CONSTRAINT {table}_bound CHECK ({bound})")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_prompt_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiExecutionGuidance',
            fields=[
                ('entity_id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('snapshot_json', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_execution_guidance',
            },
        ),
        migrations.CreateModel(
            name='AiLibraryRevision',
            fields=[
                ('version', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('config_json', models.TextField()),
                ('created_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_library_revisions',
            },
        ),
        migrations.CreateModel(
            name='AiReportRun',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('owner_email', models.CharField(max_length=320)),
                ('scope_json', models.TextField(default='null')),
                ('client_request_id', models.CharField(max_length=160)),
                ('request_digest', models.CharField(max_length=64)),
                ('snapshot_json', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.aiworkflowruns')),
            ],
            options={
                'db_table': 'ai_report_runs',
            },
        ),
        migrations.CreateModel(
            name='AiReportDelivery',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='ai_assistant.aireportrun')),
                ('channel_id', models.CharField(max_length=160)),
                ('channel_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='reserved', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_report_deliveries',
            },
        ),
        migrations.AddIndex(
            model_name='aireportrun',
            index=models.Index(fields=['owner_email', '-created_at'], name='ai_report_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='aireportrun',
            constraint=models.UniqueConstraint(fields=('owner_email', 'client_request_id'), name='ai_report_client_uq'),
        ),
        migrations.RunPython(install),
    ]
