# Generated by Django 5.2.17 on 2026-09-16 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("ai_business_evidence_runs", "ai_business_evidence_chunks"):
            cursor.execute(f"CREATE TRIGGER ai_write_fence BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION ai_runtime_write_fence()")
        cursor.execute("CREATE TRIGGER ai_immutable_evidence BEFORE UPDATE OR DELETE ON ai_business_evidence_chunks FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard()")
        cursor.execute("CREATE TRIGGER ai_immutable_identity BEFORE UPDATE ON ai_business_evidence_runs FOR EACH ROW EXECUTE FUNCTION ai_immutable_record_guard('id','owner_email','scope_json','client_request_id','request_digest','plan_json','created_at')")
        cursor.execute("""CREATE FUNCTION ai_business_terminal_guard() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$
        BEGIN
          IF TG_OP='DELETE' THEN RAISE EXCEPTION 'ai_business_delete_denied'; END IF;
          IF OLD.status<>'collecting' OR NEW.version<>OLD.version+1 THEN RAISE EXCEPTION 'ai_business_terminal_or_version'; END IF;
          RETURN NEW;
        END $$""")
        cursor.execute("CREATE TRIGGER ai_business_terminal BEFORE UPDATE OR DELETE ON ai_business_evidence_runs FOR EACH ROW EXECUTE FUNCTION ai_business_terminal_guard()")
        cursor.execute("ALTER TABLE ai_business_evidence_runs ADD CONSTRAINT ai_business_run_bound CHECK (version>=1 AND stored_bytes<=67108864 AND octet_length(plan_json)<=16000 AND octet_length(state_json)<=65536 AND scope_json='null' AND status IN ('collecting','sealed','cancelled'))")
        cursor.execute("ALTER TABLE ai_business_evidence_chunks ADD CONSTRAINT ai_business_chunk_bound CHECK (sequence>=1 AND sequence<=2000 AND octet_length(payload_json)<=131072)")


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0013_dingtalk_schedule_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiBusinessEvidenceRun',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('owner_email', models.CharField(max_length=320)),
                ('scope_json', models.TextField(default='null')),
                ('client_request_id', models.CharField(max_length=160)),
                ('request_digest', models.CharField(max_length=64)),
                ('plan_json', models.TextField()),
                ('state_json', models.TextField(default='{}')),
                ('status', models.CharField(default='collecting', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('stored_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_business_evidence_runs',
                'indexes': [models.Index(fields=['owner_email', '-created_at'], name='ai_business_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_email', 'client_request_id'), name='ai_business_client_uq')],
            },
        ),
        migrations.CreateModel(
            name='AiBusinessEvidenceChunk',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=160)),
                ('sequence', models.PositiveIntegerField()),
                ('payload_json', models.TextField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.aibusinessevidencerun')),
            ],
            options={
                'db_table': 'ai_business_evidence_chunks',
                'constraints': [models.UniqueConstraint(fields=('run', 'source_key', 'sequence'), name='ai_business_chunk_uq')],
            },
        ),
        migrations.RunPython(install),
    ]
