# Generated by Django 5.2.17 on 2026-09-01 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDataRevision',
            fields=[
                ('domain', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('source_digest', models.CharField(default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_data_revisions',
            },
        ),
        migrations.CreateModel(
            name='ProductImportFingerprint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=128, unique=True)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('import_hash', models.CharField(default='', max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('row_count', models.BigIntegerField()),
                ('published_state_token', models.CharField(max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('publication_sequence', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_import_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='ProductImportScopeHead',
            fields=[
                ('scope_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('state_token', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('current_batch_id', models.CharField(default='', max_length=128)),
                ('generation', models.BigIntegerField(default=0)),
                ('owner_started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_import_scope_heads',
            },
        ),
        migrations.CreateModel(
            name='ProductMigrationRun',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('source_path_digest', models.CharField(max_length=64)),
                ('source_snapshot_digest', models.CharField(max_length=64)),
                ('target_snapshot_digest', models.CharField(default='', max_length=64)),
                ('source_counts', models.JSONField(default=dict)),
                ('target_counts', models.JSONField(default=dict)),
                ('approved_run_id', models.CharField(default='', max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_migration_runs',
            },
        ),
        migrations.CreateModel(
            name='ProductShippingRate',
            fields=[
                ('product_code', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('shipping_rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('source_row_number', models.BigIntegerField()),
                ('last_import_batch_id', models.CharField(db_index=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'product_shipping_rates',
            },
        ),
        migrations.CreateModel(
            name='ProductWriteRequestReceipt',
            fields=[
                ('request_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('body_sha256', models.CharField(max_length=64)),
                ('query_sha256', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=200)),
                ('actor_email', models.CharField(max_length=320)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('claim_token', models.CharField(default='', max_length=64)),
                ('response_status', models.PositiveIntegerField(default=0)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_write_request_receipts',
            },
        ),
        migrations.CreateModel(
            name='ProductImportAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(default='', max_length=128)),
                ('scope_key', models.CharField(db_index=True, default='', max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('raw_file_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('row_count', models.BigIntegerField(default=0)),
                ('outcome', models.CharField(max_length=32)),
                ('error_code', models.CharField(default='', max_length=64)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_import_attempts',
                'indexes': [models.Index(fields=['scope_key', 'created_at'], name='prod_attempt_scope_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryProjection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('projection_revision', models.CharField(max_length=64)),
                ('product_code', models.CharField(max_length=512)),
                ('brand', models.TextField(default='')),
                ('available_quantity', models.BigIntegerField(default=0)),
                ('known_stock_value_cents', models.BigIntegerField(default=0)),
                ('priced_available_quantity', models.BigIntegerField(default=0)),
                ('source_batch_id', models.CharField(max_length=128)),
                ('snapshot_date', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product_inventory_projection',
                'indexes': [models.Index(fields=['projection_revision', 'product_code'], name='prod_inventory_projection_idx')],
                'constraints': [models.UniqueConstraint(fields=('projection_revision', 'product_code'), name='prod_inventory_projection_uq')],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryProjectionControl',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active_revision', models.CharField(default='', max_length=64)),
                ('active_total', models.BigIntegerField(default=0)),
                ('active_source_batch_id', models.CharField(default='', max_length=128)),
                ('active_snapshot_date', models.CharField(default='', max_length=10)),
                ('syncing_revision', models.CharField(default='', max_length=64)),
                ('syncing_total', models.BigIntegerField(default=0)),
                ('syncing_offset', models.BigIntegerField(default=0)),
                ('syncing_source_batch_id', models.CharField(default='', max_length=128)),
                ('syncing_snapshot_date', models.CharField(default='', max_length=10)),
                ('syncing_owner', models.CharField(default='', max_length=320)),
                ('owner_token_hash', models.CharField(default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_inventory_projection_control',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='prod_inventory_control_singleton_ck'), models.CheckConstraint(condition=models.Q(('active_total__gte', 0)), name='prod_inventory_active_total_ck'), models.CheckConstraint(condition=models.Q(('syncing_total__gte', 0)), name='prod_inventory_sync_total_ck'), models.CheckConstraint(condition=models.Q(('syncing_offset__gte', 0)), name='prod_inventory_sync_offset_ck')],
            },
        ),
        migrations.CreateModel(
            name='ProductRawUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('actor_email', models.CharField(max_length=320)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('chunk_size_bytes', models.BigIntegerField()),
                ('chunk_count', models.BigIntegerField()),
                ('received_chunk_count', models.BigIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='uploading', max_length=32)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('owner_generation', models.BigIntegerField(default=0)),
                ('result_batch_id', models.CharField(default='', max_length=128)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_raw_upload_sessions',
                'indexes': [models.Index(fields=['fingerprint', 'expires_at'], name='prod_upload_fingerprint_idx'), models.Index(fields=['expires_at', 'status'], name='prod_upload_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductShippingRateImportBatch',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source', models.CharField(default='sku_cumulative', max_length=64)),
                ('file_name', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('published_state_token', models.CharField(default='', max_length=64)),
                ('sheet_name', models.CharField(max_length=255)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('source_row_count', models.BigIntegerField(default=0)),
                ('row_count', models.BigIntegerField(default=0)),
                ('inserted_count', models.BigIntegerField(default=0)),
                ('updated_count', models.BigIntegerField(default=0)),
                ('duplicate_count', models.BigIntegerField(default=0)),
                ('warning_count', models.BigIntegerField(default=0)),
                ('warnings_json', models.JSONField(default=list)),
                ('totals_json', models.JSONField(default=dict)),
                ('created_at', models.TextField()),
                ('completed_at', models.TextField(blank=True, null=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'product_shipping_rate_import_batches',
                'indexes': [models.Index(fields=['created_at', 'id'], name='prod_rate_batch_created_idx'), models.Index(fields=['status', 'completed_at'], name='prod_rate_batch_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductWriteAuthority',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='d1', max_length=16)),
                ('authority_epoch', models.UUIDField(blank=True, null=True)),
                ('cutover_id', models.CharField(default='', max_length=128)),
                ('migration_verify_run_id', models.CharField(default='', max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_write_authority',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='prod_auth_singleton_ck'), models.CheckConstraint(condition=models.Q(('status__in', ['d1', 'postgres'])), name='prod_auth_status_ck'), models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('authority_epoch__isnull', True), ('cutover_id', ''), ('status', 'd1')), models.Q(('activated_at__isnull', False), ('authority_epoch__isnull', False), ('status', 'postgres'), models.Q(('cutover_id', ''), _negated=True), models.Q(('migration_verify_run_id', ''), _negated=True)), _connector='OR'), name='prod_auth_state_ck')],
            },
        ),
        migrations.CreateModel(
            name='ProductRawUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('object_key', models.TextField(unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='products.productrawuploadsession')),
            ],
            options={
                'db_table': 'product_raw_upload_chunks',
                'indexes': [models.Index(fields=['session', 'chunk_index'], name='prod_raw_chunk_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'chunk_index'), name='prod_raw_upload_chunk_uq')],
            },
        ),
    ]
