# Generated by Django 5.2.17 on 2026-09-01 15:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_control_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimportattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productimportattempt',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimportfingerprint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
