# Generated by Django 5.2.17 on 2026-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_seed_control_rows'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketannotationvalidationsample',
            name='mkt_validation_sample_uq',
        ),
        migrations.RemoveConstraint(
            model_name='marketskuannotation',
            name='mkt_sku_annotation_uq',
        ),
        migrations.RemoveIndex(
            model_name='marketskuannotation',
            name='mkt_sku_annotation_idx',
        ),
        migrations.AddField(
            model_name='marketannotationvalidationsample',
            name='image_content_sha256',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='marketannotationvalidationsample',
            name='ranking_dimension',
            field=models.CharField(default='SKU', max_length=8),
        ),
        migrations.AddField(
            model_name='marketannotationvalidationsample',
            name='scope',
            field=models.TextField(default='全部'),
        ),
        migrations.AddField(
            model_name='marketskuannotation',
            name='image_content_sha256',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='marketskuannotation',
            name='ranking_dimension',
            field=models.CharField(default='SKU', max_length=8),
        ),
        migrations.AddField(
            model_name='marketskuannotation',
            name='scope',
            field=models.TextField(default='全部'),
        ),
        migrations.AddIndex(
            model_name='marketskuannotation',
            index=models.Index(fields=['category', 'scope', 'ranking_dimension', 'segment', 'updated_at'], name='mkt_sku_annotation_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketannotationvalidationsample',
            constraint=models.UniqueConstraint(fields=('category', 'scope', 'ranking_dimension', 'sku_code', 'image_content_sha256'), name='mkt_validation_sample_uq'),
        ),
        migrations.AddConstraint(
            model_name='marketskuannotation',
            constraint=models.UniqueConstraint(fields=('category', 'scope', 'ranking_dimension', 'sku_code', 'image_content_sha256'), name='mkt_sku_annotation_uq'),
        ),
    ]
