import type { AppPrincipal, AppRole } from "@/lib/auth/authorization";

export type JsonSchema = {
  type: "object";
  properties: Record<string, unknown>;
  required?: readonly string[];
  additionalProperties: false;
  [key: string]: unknown;
};

export type AiToolAnnotations = {
  readOnlyHint: boolean;
  destructiveHint: boolean;
  idempotentHint: boolean;
  openWorldHint: boolean;
};

export type AiToolRisk = "read_only" | "write" | "dangerous";
export const aiToolSurfaces = ["ai_chat", "dingtalk_chat", "ai_agent", "ai_sandbox", "market_ai", "customer_service_ai", "codex_mcp", "test", "business_collection", "business_agent_v2", "business_agent_budget_v1", "business_agent_integrated_v1", "business_agent_screening_v1", "business_agent_screening_promotion_v1", "business_agent_screening_promotion_market_v2"] as const;
export type AiToolSurface = (typeof aiToolSurfaces)[number];
export type AiToolScopePolicy = "unscoped_only" | "principal_scope" | "metadata_safe";
export type AiToolExecutionMode = "direct" | "confirmation_required" | "background_job";
export type AiToolExecutionPolicy = {
  environment: "worker_inline" | "isolated_container";
  mode: AiToolExecutionMode;
  allowedSurfaces: readonly AiToolSurface[];
  timeoutMs: number;
  maxResultCharacters: number;
  maxCallsPerRequest: number;
};

export const AI_TOOL_EXECUTION_POLICY_LIMITS = {
  timeoutMs: { minimum: 100, maximum: 30_000 },
  maxResultCharacters: { minimum: 1_000, maximum: 40_000 },
  maxCallsPerRequest: { minimum: 1, maximum: 24 },
} as const;
const AI_TOOL_NAME_PATTERN = /^[a-z][a-z0-9_]{0,63}$/;
const INVALID_TOOL_NAME = "[invalid_tool_name]";

export type AiToolExecutionContext = {
  principal: AppPrincipal;
  surface: AiToolSurface;
  requestId: string;
  /** Generated by the server-side runtime; never accepted from model arguments. */
  invocationId?: string;
  /** Provider tool_call/tool_use id for trace correlation only, never authorization. */
  providerCallId?: string;
  /** Cooperative cancellation. Handlers using cancellable I/O should pass it through. */
  signal?: AbortSignal;
};

export type AiToolEntry = {
  name: string;
  title: string;
  description: string;
  inputSchema: JsonSchema;
  annotations: AiToolAnnotations;
  risk: AiToolRisk;
  allowedRoles: readonly AppRole[];
  scopePolicy: AiToolScopePolicy;
  execution: AiToolExecutionPolicy;
  handler: (
    arguments_: Record<string, unknown>,
    context: AiToolExecutionContext,
  ) => Promise<Record<string, unknown>>;
};

export type OpenAiToolDefinition = {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: JsonSchema;
  };
};

export type AnthropicToolDefinition = {
  name: string;
  description: string;
  input_schema: JsonSchema;
};

export type AiToolExecutionResult =
  | { ok: true; toolName: string; data: Record<string, unknown> }
  | { ok: false; toolName: string; error: { code: string; message: string }; auditStatus?: "unavailable" };

export type RegistryAuditInput = {
  requestId: string;
  invocationId: string;
  providerCallId?: string;
  actorEmail: string;
  actorRole: AppRole;
  surface: string;
  toolName: string;
  arguments: unknown;
  status: "started" | "succeeded" | "failed";
  durationMs: number;
  result?: Record<string, unknown>;
  errorCode?: string;
};

export function validateToolRegistry(entries: readonly AiToolEntry[]): void {
  const names = new Set<string>();
  const validSurfaces = new Set<AiToolSurface>(aiToolSurfaces);
  for (const entry of entries) {
    if (!AI_TOOL_NAME_PATTERN.test(entry.name)) throw new Error(`AI 工具名称无效：${entry.name}`);
    if (names.has(entry.name)) throw new Error(`AI 工具名称重复：${entry.name}`);
    names.add(entry.name);
    if (!entry.title.trim() || !entry.description.trim()) throw new Error(`AI 工具缺少标题或描述：${entry.name}`);
    if (entry.inputSchema.type !== "object" || !isRecord(entry.inputSchema.properties)) {
      throw new Error(`AI 工具 schema 必须声明 object/properties：${entry.name}`);
    }
    if (entry.inputSchema.additionalProperties !== false) throw new Error(`AI 工具 schema 必须禁止额外参数：${entry.name}`);
    for (const required of entry.inputSchema.required ?? []) {
      if (!Object.hasOwn(entry.inputSchema.properties, required)) {
        throw new Error(`AI 工具 required 字段未在 properties 中声明：${entry.name}.${required}`);
      }
    }
    if (typeof entry.handler !== "function") throw new Error(`AI 工具缺少 handler：${entry.name}`);
    if (entry.allowedRoles.length === 0) throw new Error(`AI 工具未声明角色：${entry.name}`);
    if (!["unscoped_only", "principal_scope", "metadata_safe"].includes(entry.scopePolicy)) {
      throw new Error(`AI 工具 scope 策略无效：${entry.name}`);
    }
    const policy = entry.execution;
    if (!policy || !["worker_inline", "isolated_container"].includes(policy.environment)) throw new Error(`AI 工具未声明受支持的执行环境：${entry.name}`);
    if (!["direct", "confirmation_required", "background_job"].includes(policy.mode)) {
      throw new Error(`AI 工具执行模式无效：${entry.name}`);
    }
    if (policy.allowedSurfaces.length === 0
      || new Set(policy.allowedSurfaces).size !== policy.allowedSurfaces.length
      || policy.allowedSurfaces.some((surface) => !validSurfaces.has(surface))) {
      throw new Error(`AI 工具入口范围无效：${entry.name}`);
    }
    validatePolicyInteger(entry.name, "timeoutMs", policy.timeoutMs, AI_TOOL_EXECUTION_POLICY_LIMITS.timeoutMs);
    const collector = ["get_business_source_page", "get_business_netshop_continuation_page", "get_business_sales_continuation_page", "get_business_market_continuation_page"].includes(entry.name) && policy.allowedSurfaces.length === 1
      && policy.allowedSurfaces[0] === "business_collection" && entry.risk === "read_only"
      && entry.allowedRoles.length === 1 && entry.allowedRoles[0] === "admin" && entry.scopePolicy === "unscoped_only";
    validatePolicyInteger(entry.name, "maxResultCharacters", policy.maxResultCharacters,
      collector ? { minimum: 1000, maximum: 131_072 } : AI_TOOL_EXECUTION_POLICY_LIMITS.maxResultCharacters);
    validatePolicyInteger(entry.name, "maxCallsPerRequest", policy.maxCallsPerRequest, AI_TOOL_EXECUTION_POLICY_LIMITS.maxCallsPerRequest);
    if (policy.mode === "direct" && entry.risk !== "read_only") {
      throw new Error(`写入或危险工具不能以内联直接模式执行：${entry.name}`);
    }
    if (policy.mode === "confirmation_required" && entry.risk === "read_only") {
      throw new Error(`只读工具不应声明人工确认模式：${entry.name}`);
    }
    if (entry.risk === "read_only" && (!entry.annotations.readOnlyHint || entry.annotations.destructiveHint)) {
      throw new Error(`只读工具的风险标记不一致：${entry.name}`);
    }
    if (entry.risk === "dangerous" && !entry.annotations.destructiveHint) {
      throw new Error(`危险工具必须声明 destructiveHint：${entry.name}`);
    }
  }
}

export function getToolsForPrincipal(
  principal: AppPrincipal,
  surface: AiToolSurface,
  entries: readonly AiToolEntry[],
): readonly AiToolEntry[] {
  return entries.filter((entry) => entry.allowedRoles.includes(principal.role)
    && entry.execution.allowedSurfaces.includes(surface)
    && ["worker_inline", "isolated_container"].includes(entry.execution.environment)
    && entry.execution.mode === "direct"
    && entry.risk === "read_only"
    && (principal.scope === null || entry.scopePolicy !== "unscoped_only"));
}

export function getOpenAiTools(principal: AppPrincipal, surface: AiToolSurface, entries: readonly AiToolEntry[]): OpenAiToolDefinition[] {
  if (surface === "business_collection") return [];
  return getToolsForPrincipal(principal, surface, entries).map((entry) => ({
    type: "function",
    function: { name: entry.name, description: entry.description, parameters: entry.inputSchema },
  }));
}

export function getAnthropicTools(principal: AppPrincipal, surface: AiToolSurface, entries: readonly AiToolEntry[]): AnthropicToolDefinition[] {
  if (surface === "business_collection") return [];
  return getToolsForPrincipal(principal, surface, entries).map((entry) => ({
    name: entry.name,
    description: entry.description,
    input_schema: entry.inputSchema,
  }));
}

export function getVisibleToolCatalog(principal: AppPrincipal, surface: AiToolSurface, entries: readonly AiToolEntry[]) {
  return getToolsForPrincipal(principal, surface, entries).map((entry) => ({
    name: entry.name,
    title: entry.title,
    description: entry.description,
    inputSchema: entry.inputSchema,
    annotations: entry.annotations,
    risk: entry.risk,
    scopePolicy: entry.scopePolicy,
    execution: {
      environment: entry.execution.environment,
      mode: entry.execution.mode,
      allowedSurfaces: entry.execution.allowedSurfaces,
      timeoutMs: entry.execution.timeoutMs,
      maxResultCharacters: entry.execution.maxResultCharacters,
      maxCallsPerRequest: entry.execution.maxCallsPerRequest,
    },
  }));
}

export function parseToolArguments(rawArguments: unknown): Record<string, unknown> {
  let parsed = rawArguments;
  if (typeof rawArguments === "string") {
    try {
      parsed = JSON.parse(rawArguments) as unknown;
    } catch {
      throw new RegistryToolError("invalid_arguments", "工具参数不是有效 JSON");
    }
  }
  if (!isRecord(parsed)) throw new RegistryToolError("invalid_arguments", "工具参数必须是 JSON 对象");
  return parsed;
}

export function normalizeAiToolCallName(name: string): string {
  return AI_TOOL_NAME_PATTERN.test(name) ? name : INVALID_TOOL_NAME;
}

/** Small, deterministic JSON-Schema subset used by every registered tool. */
export function validateToolArguments(value: unknown, schema: JsonSchema): void {
  validateSchemaNode(value, schema as Record<string, unknown>, "$", true);
}

export async function executeToolCallWithRegistry(
  name: string,
  rawArguments: unknown,
  context: AiToolExecutionContext,
  options: {
    entries: readonly AiToolEntry[];
    audit: (input: RegistryAuditInput) => Promise<void>;
    summarizeArguments?: (value: unknown) => unknown;
    /** Internal executor hook; deliberately never exposed to tool handlers. */
    completeExecution?: () => void;
  },
): Promise<AiToolExecutionResult> {
  name = normalizeAiToolCallName(name);
  const startedAt = performance.now();
  const entry = options.entries.find((candidate) => candidate.name === name);
  const invocationId = context.invocationId?.slice(0, 160) || crypto.randomUUID();
  const providerCallId = context.providerCallId?.slice(0, 200) || undefined;
  let parsedArguments: Record<string, unknown> = {};
  let argumentsForAudit: unknown = rawArguments;
  let argumentsValidated = false;
  const summarize = options.summarizeArguments ?? ((value: unknown) => value);
  // Only the signed internal collection surface sends the exact validated
  // handler arguments to Django. Django persists their digest, never this
  // object; every other surface retains the existing redacted summary.
  const auditArguments = () => context.surface === "business_collection" && argumentsValidated
    ? argumentsForAudit : summarize(argumentsForAudit);
  try {
    if (!entry) throw new RegistryToolError("unknown_tool", "工具不存在或未注册");
    if (!entry.allowedRoles.includes(context.principal.role)) {
      throw new RegistryToolError("forbidden", "当前账号无权调用此工具");
    }
    if (!entry.execution.allowedSurfaces.includes(context.surface)) {
      throw new RegistryToolError("forbidden", "当前入口无权调用此工具");
    }
    if (!["worker_inline", "isolated_container"].includes(entry.execution.environment)) {
      throw new RegistryToolError("unsupported_execution_environment", "当前执行器不支持该工具环境");
    }
    if (context.principal.scope !== null && entry.scopePolicy === "unscoped_only") {
      throw new RegistryToolError("forbidden", "此工具不能安全应用当前账号的数据范围");
    }
    if (entry.execution.mode === "direct" && entry.risk !== "read_only") {
      throw new RegistryToolError("forbidden", "写入或危险工具不能由当前执行环境直接执行");
    }
    if (entry.execution.mode !== "direct") {
      throw new RegistryToolError(
        entry.execution.mode === "confirmation_required" ? "confirmation_required" : "background_job_required",
        entry.execution.mode === "confirmation_required" ? "此工具必须经过服务端人工确认流程" : "此工具必须通过持久化后台任务执行",
      );
    }
    throwIfAborted(context.signal);
    parsedArguments = parseToolArguments(rawArguments);
    validateToolArguments(parsedArguments, entry.inputSchema);
    argumentsForAudit = parsedArguments;
    argumentsValidated = true;
    const preflightAudited = await tryAudit(options.audit, {
      requestId: context.requestId,
      invocationId,
      providerCallId,
      actorEmail: context.principal.email,
      actorRole: context.principal.role,
      surface: context.surface,
      toolName: name,
      arguments: auditArguments(),
      status: "started",
      durationMs: performance.now() - startedAt,
    });
    if (!preflightAudited) throw new RegistryToolError("audit_unavailable", "审计不可用，工具未执行");
    throwIfAborted(context.signal);
    const data = await entry.handler(parsedArguments, context);
    throwIfAborted(context.signal);
    validateToolResult(name, data, entry.execution.maxResultCharacters);
    options.completeExecution?.();
    throwIfAborted(context.signal);
    const audited = await tryAudit(options.audit, {
      requestId: context.requestId,
      invocationId,
      providerCallId,
      actorEmail: context.principal.email,
      actorRole: context.principal.role,
      surface: context.surface,
      toolName: name,
      arguments: auditArguments(),
      status: "succeeded",
      durationMs: performance.now() - startedAt,
      result: data,
    });
    if (!audited) {
      return { ok: false, toolName: name, error: { code: "audit_unavailable", message: "审计结果写入失败" }, auditStatus: "unavailable" };
    }
    return { ok: true, toolName: name, data };
  } catch (error) {
    const code = error instanceof RegistryToolError
      ? error.code
      : error instanceof Error && error.name === "ToolInputError"
        ? "invalid_arguments"
        : "tool_execution_failed";
    const message = code === "tool_execution_failed"
      ? "工具执行失败"
      : error instanceof Error
        ? error.message.slice(0, 240)
        : "工具调用失败";
    const audited = await tryAudit(options.audit, {
      requestId: context.requestId,
      invocationId,
      providerCallId,
      actorEmail: context.principal.email,
      actorRole: context.principal.role,
      surface: context.surface,
      toolName: name,
      arguments: auditArguments(),
      status: "failed",
      durationMs: performance.now() - startedAt,
      errorCode: code,
    });
    if (!audited) {
      return {
        ok: false,
        toolName: name,
        error: { code: "audit_unavailable", message: "审计不可用，工具执行未返回数据" },
        auditStatus: "unavailable",
      };
    }
    return { ok: false, toolName: name, error: { code, message } };
  }
}

export class RegistryToolError extends Error {
  constructor(readonly code: string, message: string) {
    super(message);
    this.name = "RegistryToolError";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

async function tryAudit(
  audit: (input: RegistryAuditInput) => Promise<void>,
  input: RegistryAuditInput,
) {
  try {
    await audit(input);
    return true;
  } catch {
    return false;
  }
}

function validateSchemaNode(value: unknown, schema: Record<string, unknown>, path: string, root = false): void {
  const fail = (message: string): never => { throw new RegistryToolError("invalid_arguments", `${path} ${message}`); };
  if (Array.isArray(schema.enum) && !schema.enum.some((candidate) => Object.is(candidate, value))) fail("不在允许值中");
  const type = schema.type;
  if (type === "object") {
    if (!isRecord(value)) return fail("必须是对象");
    const properties = isRecord(schema.properties) ? schema.properties : {};
    const required = Array.isArray(schema.required) ? schema.required.filter((item): item is string => typeof item === "string") : [];
    for (const key of required) if (!Object.hasOwn(value, key)) fail(`缺少必填字段 ${key}`);
    if (schema.additionalProperties === false) {
      const unexpected = Object.keys(value).filter((key) => !Object.hasOwn(properties, key));
      if (unexpected.length > 0) fail(`包含未声明字段 ${unexpected.join(", ")}`);
    }
    for (const [key, item] of Object.entries(value)) {
      const child = properties[key];
      if (isRecord(child)) validateSchemaNode(item, child, `${path}.${key}`);
    }
    return;
  }
  if (type === "string") {
    if (typeof value !== "string") return fail("必须是字符串");
    const length = Array.from(value).length;
    if (typeof schema.minLength === "number" && length < schema.minLength) fail(`长度不能小于 ${schema.minLength}`);
    if (typeof schema.maxLength === "number" && length > schema.maxLength) fail(`长度不能大于 ${schema.maxLength}`);
    if (typeof schema.pattern === "string" && !new RegExp(schema.pattern).test(value)) fail("格式无效");
    return;
  }
  if (type === "integer" || type === "number") {
    if (typeof value !== "number" || !Number.isFinite(value) || (type === "integer" && !Number.isSafeInteger(value))) return fail(`必须是${type === "integer" ? "整数" : "数字"}`);
    if (typeof schema.minimum === "number" && value < schema.minimum) fail(`不能小于 ${schema.minimum}`);
    if (typeof schema.maximum === "number" && value > schema.maximum) fail(`不能大于 ${schema.maximum}`);
    return;
  }
  if (type === "boolean" && typeof value !== "boolean") fail("必须是布尔值");
  if (type === "array") {
    if (!Array.isArray(value)) return fail("必须是数组");
    if (typeof schema.minItems === "number" && value.length < schema.minItems) fail(`元素不能少于 ${schema.minItems}`);
    if (typeof schema.maxItems === "number" && value.length > schema.maxItems) fail(`元素不能多于 ${schema.maxItems}`);
    if (isRecord(schema.items)) value.forEach((item, index) => validateSchemaNode(item, schema.items as Record<string, unknown>, `${path}[${index}]`));
    return;
  }
  if (!root && typeof type !== "string") fail("schema 缺少类型声明");
}

function throwIfAborted(signal: AbortSignal | undefined) {
  if (!signal?.aborted) return;
  if (signal.reason instanceof RegistryToolError) throw signal.reason;
  throw new RegistryToolError("tool_cancelled", "工具调用已取消");
}

function validatePolicyInteger(
  toolName: string,
  field: string,
  value: number,
  range: { minimum: number; maximum: number },
) {
  if (!Number.isSafeInteger(value) || value < range.minimum || value > range.maximum) {
    throw new Error(`AI 工具执行策略 ${field} 超出范围：${toolName}`);
  }
}

function validateToolResult(toolName: string, value: unknown, maxCharacters: number): asserts value is Record<string, unknown> {
  if (!isRecord(value)) throw new RegistryToolError("invalid_tool_result", "工具结果必须是 JSON 对象");
  let serialized: string | undefined;
  try {
    serialized = JSON.stringify({ ok: true, toolName, data: value });
  } catch {
    throw new RegistryToolError("invalid_tool_result", "工具结果无法序列化为 JSON");
  }
  if (typeof serialized !== "string") throw new RegistryToolError("invalid_tool_result", "工具结果无法序列化为 JSON");
  if (serialized.length > maxCharacters) {
    throw new RegistryToolError("tool_result_too_large", `工具结果信封超过 ${maxCharacters} 字符上限，请缩小查询范围或 limit`);
  }
}
