# Generated by Django 5.2.17 for the isolated finance domain.

import hashlib
import json
import uuid

from django.db import migrations, models


def _scope_key() -> str:
    domain = "finance"
    lock_scope = json.dumps(
        {"source": "monthly-finance-report"},
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    encoded = (
        f"{len(domain.encode('utf-8'))}:{domain}"
        f"{len(lock_scope.encode('utf-8'))}:{lock_scope}"
    )
    return hashlib.sha256(f"import-lock-scope-v1\n{encoded}".encode()).hexdigest()


def seed_control_rows(apps, _schema_editor):
    apps.get_model("finance", "FinanceWriteAuthority").objects.get_or_create(
        id=1, defaults={"status": "d1"}
    )
    apps.get_model("finance", "FinanceDataRevision").objects.get_or_create(
        domain="finance",
        defaults={"revision": 0, "source_digest": "0" * 64},
    )
    apps.get_model("finance", "FinanceImportScopeHead").objects.get_or_create(
        id=1,
        defaults={"scope_key": _scope_key(), "state_token": "0" * 64},
    )


def unseed_control_rows(apps, _schema_editor):
    apps.get_model("finance", "FinanceImportScopeHead").objects.filter(id=1).delete()
    apps.get_model("finance", "FinanceDataRevision").objects.filter(domain="finance").delete()
    apps.get_model("finance", "FinanceWriteAuthority").objects.filter(id=1).delete()


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceDataRevision",
            fields=[
                ("domain", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("revision", models.BigIntegerField(default=0)),
                ("source_digest", models.CharField(default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "finance_data_revisions"},
        ),
        migrations.CreateModel(
            name="FinanceImportFingerprint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("batch_id", models.CharField(max_length=64, unique=True)),
                ("scope_key", models.CharField(db_index=True, max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("raw_file_hash", models.CharField(db_index=True, max_length=64)),
                ("row_count", models.BigIntegerField()),
                ("published_state_token", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "finance_import_fingerprints"},
        ),
        migrations.CreateModel(
            name="FinanceImportScopeHead",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("scope_key", models.CharField(max_length=64, unique=True)),
                ("state_token", models.CharField(default="0" * 64, max_length=64)),
                ("status", models.CharField(default="ready", max_length=32)),
                ("owner_token", models.CharField(default="", max_length=64)),
                ("current_batch_id", models.CharField(default="", max_length=64)),
                ("generation", models.BigIntegerField(default=0)),
                ("owner_started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "finance_import_scope_heads"},
        ),
        migrations.CreateModel(
            name="FinanceMigrationRun",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("mode", models.CharField(max_length=16)),
                ("status", models.CharField(max_length=32)),
                ("source_path_digest", models.CharField(max_length=64)),
                ("source_snapshot_digest", models.CharField(max_length=64)),
                ("target_snapshot_digest", models.CharField(default="", max_length=64)),
                ("source_counts", models.JSONField(default=dict)),
                ("target_counts", models.JSONField(default=dict)),
                ("approved_run_id", models.CharField(default="", max_length=64)),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "finance_migration_runs"},
        ),
        migrations.CreateModel(
            name="FinanceTargetDeletionAudit",
            fields=[
                ("audit_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_id", models.CharField(max_length=128)),
                ("period_type", models.CharField(max_length=16)),
                ("period_key", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=100)),
                ("shop_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("actor", models.CharField(max_length=320)),
                ("old_version", models.BigIntegerField()),
                ("expected_version", models.BigIntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "finance_target_deletion_audits"},
        ),
        migrations.CreateModel(
            name="FinanceWriteAuthority",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="d1", max_length=16)),
                ("authority_epoch", models.UUIDField(blank=True, null=True)),
                ("cutover_id", models.CharField(default="", max_length=128)),
                ("migration_verify_run_id", models.CharField(default="", max_length=64)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "finance_write_authority"},
        ),
        migrations.CreateModel(
            name="FinanceWriteRequestReceipt",
            fields=[
                ("request_id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("body_sha256", models.CharField(max_length=64)),
                ("query_sha256", models.CharField(max_length=64)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=200)),
                ("actor_email", models.CharField(max_length=320)),
                ("status", models.CharField(default="processing", max_length=32)),
                ("response_status", models.PositiveIntegerField(default=0)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "finance_write_request_receipts"},
        ),
        migrations.CreateModel(
            name="FinanceImportAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("batch_id", models.CharField(default="", max_length=64)),
                ("scope_key", models.CharField(db_index=True, default="", max_length=64)),
                ("raw_file_hash", models.CharField(db_index=True, default="", max_length=64)),
                ("content_hash", models.CharField(default="", max_length=64)),
                ("outcome", models.CharField(max_length=32)),
                ("error_code", models.CharField(default="", max_length=64)),
                ("actor_email", models.CharField(default="", max_length=320)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "finance_import_attempts",
                "indexes": [models.Index(fields=["scope_key", "created_at"], name="fin_attempt_scope_idx")],
            },
        ),
        migrations.CreateModel(
            name="FinanceImportBatch",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=200)),
                ("file_name", models.TextField()),
                ("file_size_bytes", models.BigIntegerField()),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("raw_file_hash", models.CharField(db_index=True, default="", max_length=64)),
                ("content_hash", models.CharField(db_index=True, default="", max_length=64)),
                ("scope_key", models.CharField(db_index=True, default="", max_length=64)),
                ("published_state_token", models.CharField(default="", max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("row_count", models.BigIntegerField(default=0)),
                ("inserted_count", models.BigIntegerField(default=0)),
                ("duplicate_count", models.BigIntegerField(default=0)),
                ("warning_count", models.BigIntegerField(default=0)),
                ("parsed_month_count", models.BigIntegerField(default=0)),
                ("imported_month_count", models.BigIntegerField(default=0)),
                ("skipped_month_count", models.BigIntegerField(default=0)),
                ("subject_count", models.BigIntegerField(default=0)),
                ("months_json", models.JSONField(default=list)),
                ("warnings_json", models.JSONField(default=list)),
                ("actor_email", models.CharField(default="", max_length=320)),
                ("created_at", models.TextField()),
                ("completed_at", models.TextField(blank=True, null=True)),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "finance_import_batches",
                "indexes": [models.Index(fields=["created_at"], name="fin_batch_created_idx")],
            },
        ),
        migrations.CreateModel(
            name="FinanceLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=7)),
                ("section", models.CharField(max_length=32)),
                ("metric_key", models.TextField()),
                ("subject_name", models.TextField()),
                ("scope_key", models.TextField()),
                ("scope_type", models.CharField(max_length=32)),
                ("scope_name", models.TextField()),
                ("group_name", models.TextField(default="")),
                ("value_type", models.CharField(max_length=32)),
                ("amount_cents", models.BigIntegerField(blank=True, null=True)),
                ("rate_bps", models.BigIntegerField(blank=True, null=True)),
                ("raw_value", models.TextField(default="")),
                ("source_row_count", models.BigIntegerField(default=1)),
                ("sort_order", models.BigIntegerField(default=0)),
                ("is_total", models.BooleanField(default=False)),
                ("created_at", models.TextField()),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "finance_lines",
                "indexes": [
                    models.Index(fields=["month", "section", "scope_type", "scope_name"], name="fin_line_scope_idx"),
                    models.Index(fields=["metric_key", "month"], name="fin_line_metric_idx"),
                    models.Index(fields=["subject_name", "month"], name="fin_line_subject_idx"),
                    models.Index(fields=["month", "group_name", "scope_name"], name="fin_line_shop_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month", "section", "scope_key", "subject_name"),
                        name="fin_line_identity_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinanceMonth",
            fields=[
                ("month", models.CharField(max_length=7, primary_key=True, serialize=False)),
                ("batch_id", models.CharField(db_index=True, max_length=64)),
                ("sheet_name", models.TextField()),
                ("business_name", models.TextField()),
                ("source_file_name", models.TextField()),
                ("status", models.CharField(default="processing", max_length=32)),
                ("shop_count", models.BigIntegerField(default=0)),
                ("subject_count", models.BigIntegerField(default=0)),
                ("imported_at", models.TextField()),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "finance_months",
                "indexes": [
                    models.Index(fields=["status", "month"], name="fin_month_status_idx"),
                    models.Index(fields=["status", "batch_id"], name="fin_month_batch_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinanceTarget",
            fields=[
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("period_type", models.CharField(max_length=16)),
                ("period_key", models.CharField(max_length=100)),
                ("platform", models.CharField(default="", max_length=100)),
                ("shop_name", models.CharField(default="", max_length=100)),
                ("category", models.CharField(default="", max_length=100)),
                ("manager", models.CharField(default="", max_length=120)),
                ("sales_target_cents", models.BigIntegerField(default=0)),
                ("profit_target_cents", models.BigIntegerField(default=0)),
                ("small_margin_bps", models.BigIntegerField(default=0)),
                ("inventory_cleanup_target_cents", models.BigIntegerField(default=0)),
                ("promotion_fee_ratio_bps", models.BigIntegerField(default=0)),
                ("stagnant_inventory_target_cents", models.BigIntegerField(default=0)),
                ("version", models.BigIntegerField(default=1)),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "finance_targets_scoped",
                "indexes": [
                    models.Index(fields=["period_type", "period_key"], name="fin_target_period_idx"),
                    models.Index(fields=["platform", "shop_name", "period_type", "period_key"], name="fin_target_shop_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period_type", "period_key", "platform", "shop_name", "category"),
                        name="fin_target_scope_uq",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_control_rows, unseed_control_rows),
    ]
