# Generated by Django 5.2.17 on 2026-09-26 09:58

import django.db.models.deletion
from django.db import migrations, models


TABLES = (
    "finance_raw_workbook_attestations",
    "finance_raw_workbook_columns",
    "finance_raw_workbook_cells",
)
GUARD = "public.finance_raw_workbook_immutable()"
GUARD_BODY = "BEGIN RAISE EXCEPTION 'finance_raw_workbook_append_only'; END"
APP_ROLES = ("teruisi_finance_reader", "teruisi_finance_writer",
    "teruisi_ai_reader", "teruisi_ai_writer")
VARCHAR = lambda size: "character varying(" + str(size) + ")"
SCHEMA_COLUMNS = {
    TABLES[0]: {
        "id": (VARCHAR(64), True, ""),
        "month": (VARCHAR(7), True, ""),
        "finance_revision": ("bigint", True, ""),
        "finance_source_digest": (VARCHAR(64), True, ""),
        "batch_content_hash": (VARCHAR(64), True, ""),
        "batch_published_state_token": (VARCHAR(64), True, ""),
        "raw_file_sha256": (VARCHAR(64), True, ""),
        "source_sheet_count": ("integer", True, ""),
        "sheet_manifest_digest": (VARCHAR(64), True, ""),
        "parser_contract_digest": (VARCHAR(64), True, ""),
        "column_chain_digest": (VARCHAR(64), True, ""),
        "cell_chain_digest": (VARCHAR(64), True, ""),
        "column_count": ("integer", True, ""),
        "cell_count": ("integer", True, ""),
        "cross_group_same_name_risk": ("boolean", True, ""),
        "raw_workbook_bytes_observed": ("boolean", True, ""),
        "raw_workbook_bytes_retained": ("boolean", True, ""),
        "stable_netshop_shop_identity_verified": ("boolean", True, ""),
        "mapping_authority_verified": ("boolean", True, ""),
        "created_at": ("timestamp with time zone", True, ""),
        "batch_id": (VARCHAR(64), True, ""),
        "evidence_id": (VARCHAR(64), True, ""),
    },
    TABLES[1]: {
        "id": ("bigint", True, "d"),
        "column_index": ("integer", True, ""),
        "scope_key": (VARCHAR(2000), True, ""),
        "scope_type": (VARCHAR(16), True, ""),
        "scope_name": (VARCHAR(1000), True, ""),
        "group_name": (VARCHAR(1000), True, ""),
        "header_digest": (VARCHAR(64), True, ""),
        "source_column_digest": (VARCHAR(64), True, ""),
        "attestation_id": (VARCHAR(64), True, ""),
        "evidence_column_id": ("bigint", True, ""),
    },
    TABLES[2]: {
        "id": ("bigint", True, "d"),
        "section": (VARCHAR(32), True, ""),
        "row_index": ("integer", True, ""),
        "column_index": ("integer", True, ""),
        "subject_name": (VARCHAR(2000), True, ""),
        "metric_key": (VARCHAR(500), True, ""),
        "value_type": (VARCHAR(16), True, ""),
        "amount_cents": ("bigint", False, ""),
        "rate_bps": ("bigint", False, ""),
        "raw_value_digest": (VARCHAR(64), True, ""),
        "source_cell_digest": (VARCHAR(64), True, ""),
        "is_total": ("boolean", True, ""),
        "attestation_id": (VARCHAR(64), True, ""),
        "evidence_cell_id": ("bigint", True, ""),
        "column_id": ("bigint", True, ""),
    },
}
SCHEMA_NAMED_CONSTRAINTS = {
    TABLES[0]: {
        "finance_raw_workbook_attestations_pkey": ("p", ("id",), None),
        "finance_raw_workbook_attestations_evidence_id_key":
            ("u", ("evidence_id",), None),
        "fin_workbook_month_batch_uq": ("u", ("month", "batch_id"), None),
        "fin_workbook_bytes_observed": ("c", (), "checkraw_workbook_bytes_observed"),
        "fin_workbook_bytes_not_retained": ("c", (), "checknotraw_workbook_bytes_retained"),
        "fin_workbook_shop_unverified": ("c", (), "checknotstable_netshop_shop_identity_verified"),
        "fin_workbook_mapping_unverified": ("c", (), "checknotmapping_authority_verified"),
        "finance_raw_workbook_attestations_source_sheet_count_check":
            ("c", (), "checksource_sheet_count>=0"),
        "finance_raw_workbook_attestations_column_count_check":
            ("c", (), "checkcolumn_count>=0"),
        "finance_raw_workbook_attestations_cell_count_check":
            ("c", (), "checkcell_count>=0"),
    },
    TABLES[1]: {
        "finance_raw_workbook_columns_pkey": ("p", ("id",), None),
        "finance_raw_workbook_columns_evidence_column_id_key":
            ("u", ("evidence_column_id",), None),
        "fin_workbook_column_uq": ("u", ("attestation_id", "column_index"), None),
        "finance_raw_workbook_columns_column_index_check":
            ("c", (), "checkcolumn_index>=0"),
    },
    TABLES[2]: {
        "finance_raw_workbook_cells_pkey": ("p", ("id",), None),
        "finance_raw_workbook_cells_evidence_cell_id_key":
            ("u", ("evidence_cell_id",), None),
        "fin_workbook_cell_uq": ("u", ("attestation_id", "section",
            "row_index", "column_index"), None),
        "finance_raw_workbook_cells_row_index_check":
            ("c", (), "checkrow_index>=0"),
        "finance_raw_workbook_cells_column_index_check":
            ("c", (), "checkcolumn_index>=0"),
    },
}
SCHEMA_FOREIGN_KEYS = {
    TABLES[0]: {("batch_id", "finance_import_batches"),
        ("evidence_id", "finance_raw_column_evidence_months")},
    TABLES[1]: {("attestation_id", TABLES[0]),
        ("evidence_column_id", "finance_raw_column_evidence_columns")},
    TABLES[2]: {("attestation_id", TABLES[0]),
        ("column_id", TABLES[1]),
        ("evidence_cell_id", "finance_raw_column_evidence_cells")},
}


def _compact_check(value):
    return "".join(ch for ch in value.lower()
        if ch not in ' \t\r\n()"')


def verify_catalog(cursor, *, allow_deferred_fk=False):
    cursor.execute("SELECT prosrc,prosecdef,proconfig,proowner,proacl "
        "FROM pg_catalog.pg_proc WHERE oid=to_regprocedure(%s)", [GUARD])
    guard = cursor.fetchone()
    cursor.execute("SELECT proowner FROM pg_catalog.pg_proc "
        "WHERE oid=to_regprocedure('public."
        "finance_raw_column_evidence_immutable()')")
    predecessor = cursor.fetchone()
    if (guard is None or guard[0].strip() != GUARD_BODY
            or guard[1] is not False
            or {str(item).replace(" ", "") for item in (guard[2] or [])} !=
                {"search_path=pg_catalog,public"}
            or guard[4] is None
            or predecessor is None or guard[3] != predecessor[0]):
        raise RuntimeError("finance.0006 guard function drift")
    cursor.execute("SELECT count(*) FROM pg_catalog.pg_proc p, "
        "LATERAL pg_catalog.aclexplode(p.proacl) acl "
        "WHERE p.oid=to_regprocedure(%s) AND acl.grantee=0 "
        "AND acl.privilege_type='EXECUTE'", [GUARD])
    if cursor.fetchone() != (0,):
        raise RuntimeError("finance.0006 guard function public EXECUTE")
    cursor.execute("SELECT count(*) FROM pg_catalog.pg_proc p, "
        "LATERAL pg_catalog.aclexplode(p.proacl) acl "
        "WHERE p.oid=to_regprocedure(%s) AND acl.grantee<>p.proowner",
        [GUARD])
    if cursor.fetchone() != (0,):
        raise RuntimeError("finance.0006 guard function extra EXECUTE")
    for table in TABLES:
        cursor.execute("SELECT relkind,relowner FROM pg_catalog.pg_class "
            "WHERE oid=%s::regclass", ["public." + table])
        relation = cursor.fetchone()
        if relation != ("r", guard[3]):
            raise RuntimeError("finance.0006 table owner/kind drift")
        cursor.execute("SELECT a.attname,pg_catalog.format_type(a.atttypid,"
            "a.atttypmod),a.attnotnull,a.attidentity "
            "FROM pg_catalog.pg_attribute a WHERE a.attrelid=%s::regclass "
            "AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum",
            ["public." + table])
        actual_columns = {name: (kind, required, identity)
            for name, kind, required, identity in cursor.fetchall()}
        if actual_columns != SCHEMA_COLUMNS[table]:
            raise RuntimeError("finance.0006 physical columns drift")
        cursor.execute("SELECT c.conname,c.contype,c.convalidated,"
            "c.condeferrable,c.condeferred,c.confdeltype,"
            "c.confrelid::regclass::text,"
            "pg_catalog.pg_get_constraintdef(c.oid),"
            "ARRAY(SELECT a.attname FROM unnest(c.conkey) WITH ORDINALITY "
            "AS k(attnum,ord) JOIN pg_catalog.pg_attribute a ON "
            "a.attrelid=c.conrelid AND a.attnum=k.attnum "
            "ORDER BY k.ord) "
            "FROM pg_catalog.pg_constraint c WHERE c.conrelid=%s::regclass",
            ["public." + table])
        actual_named = {}
        actual_fks = []
        for (name, kind, validated, defer, deferred, delete_kind,
                target, definition, names) in cursor.fetchall():
            if not validated:
                raise RuntimeError("finance.0006 constraint unvalidated")
            columns = tuple(names or ())
            if kind == "c":
                # The exact pg_get_constraintdef expression pins the checked
                # column. pg_constraint.conkey is not a stable contract for
                # CHECK across backend-generated equivalent forms.
                columns = ()
            if kind == "f":
                if (not defer or not deferred or delete_kind != "a"
                        or len(columns) != 1):
                    raise RuntimeError("finance.0006 FK action/deferral drift")
                actual_fks.append((columns[0], target.rsplit(".", 1)[-1]))
            else:
                if defer or deferred or kind not in {"p", "u", "c"}:
                    raise RuntimeError("finance.0006 key/check deferral drift")
                actual_named[name] = (kind, columns,
                    _compact_check(definition) if kind == "c" else None)
        expected_fks = SCHEMA_FOREIGN_KEYS[table]
        fks_valid = (len(actual_fks) == len(expected_fks)
            and set(actual_fks) == expected_fks)
        if allow_deferred_fk:
            fks_valid = (len(actual_fks) == len(set(actual_fks))
                and set(actual_fks) <= expected_fks)
        if actual_named != SCHEMA_NAMED_CONSTRAINTS[table] or not fks_valid:
            expected_named = SCHEMA_NAMED_CONSTRAINTS[table]
            missing = sorted(set(expected_named) - set(actual_named))[:5]
            extra = sorted(set(actual_named) - set(expected_named))[:5]
            changed = sorted(name for name in set(actual_named) &
                set(expected_named) if actual_named[name] !=
                expected_named[name])[:5]
            raise RuntimeError("finance.0006 key/FK/CHECK definition drift: "
                + table + " missing=" + repr(missing) + " extra=" +
                repr(extra) + " changed=" + repr(changed) +
                " fkCount=" + str(len(actual_fks)))
        cursor.execute("SELECT count(*) FROM pg_catalog.pg_class c, "
            "LATERAL pg_catalog.aclexplode(c.relacl) acl "
            "WHERE c.oid=%s::regclass AND acl.grantee<>c.relowner",
            ["public." + table])
        if cursor.fetchone() != (0,):
            raise RuntimeError("finance.0006 table extra role ACL")
        cursor.execute("SELECT count(*) FROM pg_catalog.pg_attribute a "
            "JOIN pg_catalog.pg_class c ON c.oid=a.attrelid, "
            "LATERAL pg_catalog.aclexplode(a.attacl) acl "
            "WHERE a.attrelid=%s::regclass AND a.attnum>0 "
            "AND NOT a.attisdropped AND acl.grantee<>c.relowner",
            ["public." + table])
        if cursor.fetchone() != (0,):
            raise RuntimeError("finance.0006 column extra role ACL")
        cursor.execute("SELECT tgname,tgenabled,tgtype,tgqual,tgfoid "
            "FROM pg_catalog.pg_trigger WHERE tgrelid=%s::regclass "
            "AND NOT tgisinternal ORDER BY tgname", ["public." + table])
        triggers = cursor.fetchall()
        cursor.execute("SELECT to_regprocedure(%s)::oid", [GUARD])
        guard_oid = cursor.fetchone()[0]
        cursor.execute("SELECT to_regprocedure('public."
            "finance_raw_column_evidence_immutable()')::oid")
        old_guard_oid = cursor.fetchone()[0]
        if (len(triggers) != 2
                or triggers[0][:4] != (
                    "fin_workbook_immutable_row", "O", 27, None)
                or triggers[0][4] != guard_oid
                or triggers[1][:4] != (
                    "fin_workbook_no_truncate", "O", 34, None)
                or triggers[1][4] != old_guard_oid):
            raise RuntimeError("finance.0006 immutable trigger drift")
        cursor.execute("SELECT rolname FROM pg_catalog.pg_roles "
            "WHERE rolname=ANY(%s)", [list(APP_ROLES)])
        for (role,) in cursor.fetchall():
            for privilege in ("SELECT", "INSERT", "UPDATE", "DELETE",
                    "TRUNCATE", "REFERENCES", "TRIGGER"):
                cursor.execute("SELECT has_table_privilege(%s,%s,%s)",
                    [role, "public." + table, privilege])
                if cursor.fetchone() != (False,):
                    raise RuntimeError("finance.0006 application table ACL drift")
            for privilege in ("SELECT", "INSERT", "UPDATE"):
                cursor.execute("SELECT has_any_column_privilege(%s,%s,%s)",
                    [role, "public." + table, privilege])
                if cursor.fetchone() != (False,):
                    raise RuntimeError("finance.0006 application column ACL drift")


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE FUNCTION " + GUARD + " RETURNS trigger "
            "LANGUAGE plpgsql SET search_path=pg_catalog,public AS $$ "
            + GUARD_BODY + " $$")
        cursor.execute("REVOKE ALL ON FUNCTION " + GUARD + " FROM PUBLIC")
        for table in TABLES:
            cursor.execute("REVOKE ALL ON TABLE public." + table +
                " FROM PUBLIC")
            for role in APP_ROLES:
                cursor.execute("SELECT to_regrole(%s)", [role])
                if cursor.fetchone()[0] is not None:
                    cursor.execute("REVOKE ALL ON TABLE public." + table +
                        " FROM " + role)
            cursor.execute("CREATE TRIGGER fin_workbook_immutable_row "
                "BEFORE UPDATE OR DELETE ON public." + table +
                " FOR EACH ROW EXECUTE FUNCTION " + GUARD)
            cursor.execute("CREATE TRIGGER fin_workbook_no_truncate "
                "BEFORE TRUNCATE ON public." + table +
                " FOR EACH STATEMENT EXECUTE FUNCTION "
                "public.finance_raw_column_evidence_immutable()")
        verify_catalog(cursor, allow_deferred_fk=True)


def uninstall_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in TABLES:
            cursor.execute("SELECT EXISTS(SELECT 1 FROM public." + table + ")")
            if cursor.fetchone() != (False,):
                raise RuntimeError("finance.0006 cannot discard attested workbook")
            cursor.execute("DROP TRIGGER fin_workbook_immutable_row ON public." +
                table)
            cursor.execute("DROP TRIGGER fin_workbook_no_truncate ON public." +
                table)
        cursor.execute("DROP FUNCTION " + GUARD)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_raw_column_evidence_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRawWorkbookAttestation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('finance_revision', models.BigIntegerField()),
                ('finance_source_digest', models.CharField(max_length=64)),
                ('batch_content_hash', models.CharField(max_length=64)),
                ('batch_published_state_token', models.CharField(max_length=64)),
                ('raw_file_sha256', models.CharField(max_length=64)),
                ('source_sheet_count', models.PositiveIntegerField()),
                ('sheet_manifest_digest', models.CharField(max_length=64)),
                ('parser_contract_digest', models.CharField(max_length=64)),
                ('column_chain_digest', models.CharField(max_length=64)),
                ('cell_chain_digest', models.CharField(max_length=64)),
                ('column_count', models.PositiveIntegerField()),
                ('cell_count', models.PositiveIntegerField()),
                ('cross_group_same_name_risk', models.BooleanField(default=False)),
                ('raw_workbook_bytes_observed', models.BooleanField(default=True)),
                ('raw_workbook_bytes_retained', models.BooleanField(default=False)),
                ('stable_netshop_shop_identity_verified', models.BooleanField(default=False)),
                ('mapping_authority_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financeimportbatch')),
                ('evidence', models.OneToOneField(db_column='evidence_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawevidencemonth')),
            ],
            options={
                'db_table': 'finance_raw_workbook_attestations',
            },
        ),
        migrations.CreateModel(
            name='FinanceRawWorkbookColumn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('column_index', models.PositiveIntegerField()),
                ('scope_key', models.CharField(max_length=2000)),
                ('scope_type', models.CharField(max_length=16)),
                ('scope_name', models.CharField(max_length=1000)),
                ('group_name', models.CharField(max_length=1000)),
                ('header_digest', models.CharField(max_length=64)),
                ('source_column_digest', models.CharField(max_length=64)),
                ('attestation', models.ForeignKey(db_column='attestation_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawworkbookattestation')),
                ('evidence_column', models.OneToOneField(db_column='evidence_column_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawevidencecolumn')),
            ],
            options={
                'db_table': 'finance_raw_workbook_columns',
            },
        ),
        migrations.CreateModel(
            name='FinanceRawWorkbookCell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=32)),
                ('row_index', models.PositiveIntegerField()),
                ('column_index', models.PositiveIntegerField()),
                ('subject_name', models.CharField(max_length=2000)),
                ('metric_key', models.CharField(max_length=500)),
                ('value_type', models.CharField(max_length=16)),
                ('amount_cents', models.BigIntegerField(null=True)),
                ('rate_bps', models.BigIntegerField(null=True)),
                ('raw_value_digest', models.CharField(max_length=64)),
                ('source_cell_digest', models.CharField(max_length=64)),
                ('is_total', models.BooleanField(default=False)),
                ('attestation', models.ForeignKey(db_column='attestation_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawworkbookattestation')),
                ('evidence_cell', models.OneToOneField(db_column='evidence_cell_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawevidencecell')),
                ('column', models.ForeignKey(db_column='column_id', on_delete=django.db.models.deletion.PROTECT, to='finance.financerawworkbookcolumn')),
            ],
            options={
                'db_table': 'finance_raw_workbook_cells',
            },
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookattestation',
            constraint=models.UniqueConstraint(fields=('month', 'batch'), name='fin_workbook_month_batch_uq'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookattestation',
            constraint=models.CheckConstraint(condition=models.Q(('raw_workbook_bytes_observed', True)), name='fin_workbook_bytes_observed'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookattestation',
            constraint=models.CheckConstraint(condition=models.Q(('raw_workbook_bytes_retained', False)), name='fin_workbook_bytes_not_retained'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookattestation',
            constraint=models.CheckConstraint(condition=models.Q(('stable_netshop_shop_identity_verified', False)), name='fin_workbook_shop_unverified'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookattestation',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_authority_verified', False)), name='fin_workbook_mapping_unverified'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookcolumn',
            constraint=models.UniqueConstraint(fields=('attestation', 'column_index'), name='fin_workbook_column_uq'),
        ),
        migrations.AddConstraint(
            model_name='financerawworkbookcell',
            constraint=models.UniqueConstraint(fields=('attestation', 'section', 'row_index', 'column_index'), name='fin_workbook_cell_uq'),
        ),
        migrations.RunPython(install_guards, uninstall_guards),
    ]
