import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDataRevision',
            fields=[
                ('domain', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('revision', models.BigIntegerField(default=0)),
                ('source_digest', models.CharField(default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_data_revisions',
            },
        ),
        migrations.CreateModel(
            name='InventoryImportFingerprint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(db_index=True, max_length=16)),
                ('batch_id', models.CharField(max_length=128, unique=True)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('import_hash', models.CharField(default='', max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('row_count', models.BigIntegerField()),
                ('published_state_token', models.CharField(max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory_import_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='InventoryImportScopeHead',
            fields=[
                ('dataset', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=64, unique=True)),
                ('state_token', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('current_batch_id', models.CharField(default='', max_length=128)),
                ('generation', models.BigIntegerField(default=0)),
                ('owner_started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_import_scope_heads',
            },
        ),
        migrations.CreateModel(
            name='InventoryMigrationRun',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('source_path_digest', models.CharField(max_length=64)),
                ('source_snapshot_digest', models.CharField(max_length=64)),
                ('target_snapshot_digest', models.CharField(default='', max_length=64)),
                ('source_counts', models.JSONField(default=dict)),
                ('target_counts', models.JSONField(default=dict)),
                ('approved_run_id', models.CharField(default='', max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_migration_runs',
            },
        ),
        migrations.CreateModel(
            name='InventoryWriteRequestReceipt',
            fields=[
                ('request_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('body_sha256', models.CharField(max_length=64)),
                ('query_sha256', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=200)),
                ('actor_email', models.CharField(max_length=320)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('claim_token', models.CharField(default='', max_length=64)),
                ('response_status', models.PositiveIntegerField(default=0)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_write_request_receipts',
            },
        ),
        migrations.CreateModel(
            name='InventoryAgeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=128)),
                ('row_key', models.CharField(max_length=512)),
                ('source_row_number', models.BigIntegerField()),
                ('snapshot_date', models.DateField(db_index=True)),
                ('warehouse', models.TextField()),
                ('warehouse_type', models.CharField(default='other', max_length=32)),
                ('product_code', models.CharField(db_index=True, max_length=512)),
                ('product_name', models.TextField(default='')),
                ('specification', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('available_quantity', models.BigIntegerField(default=0)),
                ('inventory_age_days', models.IntegerField(blank=True, null=True)),
                ('sales_7d_quantity', models.BigIntegerField(blank=True, null=True)),
                ('sales_30d_quantity', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost_cents', models.BigIntegerField(default=0)),
                ('stock_value_cents', models.BigIntegerField(blank=True, null=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'inventory_age_lines',
                'indexes': [models.Index(fields=['batch_id', 'warehouse', 'product_code'], name='inv_age_lookup_idx'), models.Index(fields=['snapshot_date', 'product_code'], name='inv_age_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch_id', 'row_key'), name='inv_age_batch_row_uq'), models.UniqueConstraint(fields=('snapshot_date', 'row_key'), name='inv_age_snapshot_row_uq')],
            },
        ),
        migrations.CreateModel(
            name='InventoryImportAttempt',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('dataset', models.CharField(db_index=True, max_length=16)),
                ('batch_id', models.CharField(default='', max_length=128)),
                ('scope_key', models.CharField(db_index=True, default='', max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('raw_file_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('row_count', models.BigIntegerField(default=0)),
                ('excluded_count', models.BigIntegerField(default=0)),
                ('outcome', models.CharField(max_length=32)),
                ('error_code', models.CharField(default='', max_length=64)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_import_attempts',
                'indexes': [models.Index(fields=['dataset', 'scope_key', 'created_at'], name='inv_attempt_scope_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryImportBatch',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('dataset', models.CharField(db_index=True, max_length=16)),
                ('source', models.CharField(max_length=128)),
                ('file_name', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('published_state_token', models.CharField(default='', max_length=64)),
                ('sheet_name', models.CharField(max_length=255)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('source_row_count', models.BigIntegerField(default=0)),
                ('row_count', models.BigIntegerField(default=0)),
                ('inserted_count', models.BigIntegerField(default=0)),
                ('excluded_count', models.BigIntegerField(default=0)),
                ('warning_count', models.BigIntegerField(default=0)),
                ('warnings_json', models.JSONField(default=list)),
                ('totals_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'inventory_import_batches',
                'indexes': [models.Index(fields=['dataset', 'snapshot_date', 'status', 'completed_at'], name='inv_batch_scope_idx'), models.Index(fields=['created_at', 'id'], name='inv_batch_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryOperatingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('target_days', models.PositiveIntegerField(default=30)),
                ('critical_days', models.PositiveIntegerField(default=7)),
                ('slow_days', models.PositiveIntegerField(default=45)),
                ('stagnant_days', models.PositiveIntegerField(default=90)),
                ('auto_replenishment', models.BooleanField(default=False)),
                ('inventory_alert', models.BooleanField(default=True)),
                ('allow_negative_inventory', models.BooleanField(default=False)),
                ('updated_by', models.CharField(default='', max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_operating_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='inv_settings_singleton_ck')],
            },
        ),
        migrations.CreateModel(
            name='InventoryRawUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('dataset', models.CharField(max_length=16)),
                ('snapshot_date', models.DateField(blank=True, null=True)),
                ('actor_email', models.CharField(max_length=320)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('chunk_size_bytes', models.BigIntegerField()),
                ('chunk_count', models.BigIntegerField()),
                ('received_chunk_count', models.BigIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='uploading', max_length=32)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('owner_generation', models.BigIntegerField(default=0)),
                ('result_batch_id', models.CharField(default='', max_length=128)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory_raw_upload_sessions',
                'indexes': [models.Index(fields=['fingerprint', 'expires_at'], name='inv_upload_fingerprint_idx'), models.Index(fields=['expires_at', 'status'], name='inv_upload_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=128)),
                ('row_key', models.CharField(max_length=512)),
                ('source_row_number', models.BigIntegerField()),
                ('snapshot_date', models.DateField(db_index=True)),
                ('warehouse', models.TextField()),
                ('warehouse_type', models.CharField(default='other', max_length=32)),
                ('product_code', models.CharField(db_index=True, max_length=512)),
                ('product_name', models.TextField(default='')),
                ('brand', models.TextField(default='')),
                ('specification', models.TextField(default='')),
                ('barcode', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('on_hand_quantity', models.BigIntegerField(default=0)),
                ('available_quantity', models.BigIntegerField(default=0)),
                ('locked_quantity', models.BigIntegerField(default=0)),
                ('in_transit_quantity', models.BigIntegerField(default=0)),
                ('unit_cost_cents', models.BigIntegerField(default=0)),
                ('inventory_age_days', models.IntegerField(blank=True, null=True)),
                ('sales_7d_quantity', models.BigIntegerField(blank=True, null=True)),
                ('sales_30d_quantity', models.BigIntegerField(blank=True, null=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'inventory_stock_lines',
                'indexes': [models.Index(fields=['batch_id', 'warehouse', 'product_code'], name='inv_stock_lookup_idx'), models.Index(fields=['snapshot_date', 'product_code'], name='inv_stock_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch_id', 'row_key'), name='inv_stock_batch_row_uq'), models.UniqueConstraint(fields=('snapshot_date', 'row_key'), name='inv_stock_snapshot_row_uq')],
            },
        ),
        migrations.CreateModel(
            name='InventoryWriteAuthority',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='d1', max_length=16)),
                ('authority_epoch', models.UUIDField(blank=True, null=True)),
                ('cutover_id', models.CharField(default='', max_length=128)),
                ('migration_verify_run_id', models.CharField(default='', max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_write_authority',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='inv_auth_singleton_ck'), models.CheckConstraint(condition=models.Q(('status__in', ['d1', 'postgres'])), name='inv_auth_status_ck'), models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('authority_epoch__isnull', True), ('cutover_id', ''), ('status', 'd1')), models.Q(('activated_at__isnull', False), ('authority_epoch__isnull', False), ('status', 'postgres'), models.Q(('cutover_id', ''), _negated=True), models.Q(('migration_verify_run_id', ''), _negated=True)), _connector='OR'), name='inv_auth_state_ck')],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentPlanItem',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_batch_id', models.CharField(db_index=True, max_length=128)),
                ('product_code', models.CharField(db_index=True, max_length=512)),
                ('product_name', models.TextField()),
                ('warehouse', models.TextField()),
                ('suggested_quantity', models.BigIntegerField()),
                ('planned_quantity', models.BigIntegerField()),
                ('coverage_days_tenths', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(default='')),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('created_by', models.CharField(default='', max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'replenishment_plan_items',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='inv_plan_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('source_batch_id', 'warehouse', 'product_code', 'status'), name='inv_plan_active_draft_uq')],
            },
        ),
        migrations.CreateModel(
            name='InventoryRawUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('object_key', models.TextField(unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='inventory.inventoryrawuploadsession')),
            ],
            options={
                'db_table': 'inventory_raw_upload_chunks',
                'indexes': [models.Index(fields=['session', 'chunk_index'], name='inv_raw_chunk_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'chunk_index'), name='inv_raw_upload_chunk_uq')],
            },
        ),
    ]
