# Generated by Django 5.2.17 on 2026-09-08 09:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_replenishment_group_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuangdongMonitorAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=255)),
                ('raw_hash', models.CharField(default='', max_length=64)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('actor', models.CharField(max_length=320)),
                ('status', models.CharField(max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory_guangdong_monitor_audits',
            },
        ),
        migrations.CreateModel(
            name='GuangdongMonitorItem',
            fields=[
                ('product_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('updated_by', models.CharField(max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_guangdong_monitor_items',
            },
        ),
        migrations.CreateModel(
            name='GuangdongSupplierCycle',
            fields=[
                ('supplier', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('lead_days', models.PositiveSmallIntegerField()),
                ('buffer_days', models.PositiveSmallIntegerField(default=7)),
                ('updated_by', models.CharField(max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_guangdong_supplier_cycles',
                'constraints': [models.CheckConstraint(condition=models.Q(('lead_days__gte', 1), ('lead_days__lte', 365)), name='inv_gd_lead_bounds'), models.CheckConstraint(condition=models.Q(('buffer_days__gte', 0), ('buffer_days__lte', 365)), name='inv_gd_buffer_bounds')],
            },
        ),
    ]
