# Generated for Django 5.2; kept in source control so bootstrap is deterministic.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErpProductMaster",
            fields=[
                ("product_code", models.TextField(primary_key=True, serialize=False)),
                ("product_name", models.TextField()),
                ("brand", models.TextField(default="")),
                ("specification", models.TextField(default="")),
                ("barcode", models.TextField(default="")),
                ("category", models.TextField(default="")),
                ("supplier", models.TextField(default="")),
                ("product_status", models.TextField(default="")),
                ("source_row_number", models.BigIntegerField()),
                ("last_import_batch_id", models.TextField()),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "erp_product_master",
                "indexes": [
                    models.Index(fields=["product_name"], name="erp_product_name_idx"),
                    models.Index(fields=["barcode"], name="erp_product_barcode_idx"),
                    models.Index(fields=["last_import_batch_id"], name="erp_product_batch_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesDataRevision",
            fields=[
                ("domain", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("revision", models.BigIntegerField(default=0)),
                ("source_digest", models.CharField(default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "sales_data_revisions"},
        ),
        migrations.CreateModel(
            name="SalesImportBatch",
            fields=[
                ("id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=200)),
                ("file_name", models.TextField()),
                ("file_size_bytes", models.BigIntegerField()),
                ("file_hash", models.CharField(max_length=128, unique=True)),
                ("sheet_name", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("row_count", models.BigIntegerField(default=0)),
                ("inserted_count", models.BigIntegerField(default=0)),
                ("duplicate_count", models.BigIntegerField(default=0)),
                ("warning_count", models.BigIntegerField(default=0)),
                ("warnings_json", models.TextField(default="[]")),
                ("totals_json", models.TextField(default="{}")),
                ("created_at", models.TextField()),
                ("completed_at", models.TextField(blank=True, null=True)),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "sales_import_batches",
                "indexes": [models.Index(fields=["created_at"], name="sales_batch_created_idx")],
            },
        ),
        migrations.CreateModel(
            name="SalesMigrationLock",
            fields=[
                ("name", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("owner_id", models.CharField(default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "sales_migration_locks"},
        ),
        migrations.CreateModel(
            name="SalesMigrationRun",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=32)),
                ("dry_run", models.BooleanField(default=False)),
                ("source_fingerprint", models.CharField(max_length=128)),
                ("source_path_digest", models.CharField(max_length=64)),
                ("generation", models.CharField(max_length=64)),
                ("source_revision", models.CharField(default="", max_length=64)),
                ("target_revision", models.CharField(default="", max_length=64)),
                ("source_counts", models.JSONField(default=dict)),
                ("target_counts", models.JSONField(default=dict)),
                ("source_digests", models.JSONField(default=dict)),
                ("target_digests", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sales_migration_runs",
                "indexes": [models.Index(fields=["status", "started_at"], name="sales_migration_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_line_key", models.TextField(unique=True)),
                ("source_row_hash", models.TextField()),
                ("first_import_batch_id", models.TextField()),
                ("last_import_batch_id", models.TextField()),
                ("source_row_number", models.BigIntegerField()),
                ("order_no", models.TextField()),
                ("online_order_no", models.TextField()),
                ("channel", models.TextField()),
                ("platform", models.TextField()),
                ("shop_name", models.TextField()),
                ("logistics_company", models.TextField()),
                ("warehouse", models.TextField()),
                ("product_code", models.TextField()),
                ("online_spec_code", models.TextField(default="")),
                ("product_name", models.TextField()),
                ("specification", models.TextField()),
                ("barcode", models.TextField()),
                ("supplier", models.TextField()),
                ("category", models.TextField()),
                ("quantity", models.BigIntegerField()),
                ("list_unit_price_cents", models.BigIntegerField()),
                ("cost_amount_cents", models.BigIntegerField()),
                ("allocated_unit_price_cents", models.BigIntegerField()),
                ("allocated_amount_cents", models.BigIntegerField()),
                ("fee_allocation_cents", models.BigIntegerField()),
                ("gross_profit_cents", models.BigIntegerField()),
                ("gross_margin_bps", models.BigIntegerField()),
                ("untaxed_gross_profit_cents", models.BigIntegerField()),
                ("untaxed_gross_margin_bps", models.BigIntegerField()),
                ("order_time", models.TextField()),
                ("sales_time", models.TextField()),
                ("ship_time", models.TextField()),
                ("line_ship_time", models.TextField()),
                ("business_type", models.TextField()),
                ("created_at", models.TextField()),
                ("updated_at", models.TextField()),
                ("migration_generation", models.CharField(db_index=True, default="", max_length=64)),
            ],
            options={
                "db_table": "sales_order_lines",
                "indexes": [
                    models.Index(fields=["ship_time"], name="sales_line_ship_idx"),
                    models.Index(fields=["sales_time"], name="sales_line_sale_idx"),
                    models.Index(fields=["channel"], name="sales_line_channel_idx"),
                    models.Index(fields=["platform"], name="sales_line_platform_idx"),
                    models.Index(fields=["product_code"], name="sales_line_product_idx"),
                    models.Index(fields=["last_import_batch_id"], name="sales_line_batch_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="INSERT INTO sales_migration_locks (name, owner_id, updated_at) VALUES ('sales_snapshot', '', CURRENT_TIMESTAMP)",
            reverse_sql="DELETE FROM sales_migration_locks WHERE name = 'sales_snapshot'",
        ),
    ]
