# Generated by Django 5.2.17 on 2026-08-28 11:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_pending_sales_write_authority(apps, _schema_editor):
    authority = apps.get_model("sales", "SalesWriteAuthority")
    authority.objects.get_or_create(id=1, defaults={"status": "pending"})


def delete_pending_sales_write_authority(apps, _schema_editor):
    authority = apps.get_model("sales", "SalesWriteAuthority")
    authority.objects.filter(id=1, status="pending", cutover_id="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_projection_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesimportbatch",
            name="actor_email",
            field=models.CharField(default="", max_length=320),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="content_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="published_state_token",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="raw_file_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="scope_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="salesimportbatch",
            name="scope_key",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="SalesImportAttempt",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("domain", models.CharField(default="sales", max_length=32)),
                ("session_id", models.CharField(blank=True, default="", max_length=36)),
                ("batch_id", models.CharField(blank=True, default="", max_length=128)),
                ("scope_key", models.CharField(blank=True, default="", max_length=64)),
                ("scope_json", models.JSONField(default=dict)),
                ("import_hash", models.CharField(blank=True, default="", max_length=64)),
                ("raw_file_hash", models.CharField(default="", max_length=64)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("row_count", models.BigIntegerField(default=0)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("actor_email", models.CharField(blank=True, default="", max_length=320)),
                ("warnings", models.JSONField(default=list)),
                ("outcome", models.CharField(max_length=32)),
                ("error_code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "recovered_from_attempt_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sales_import_attempts",
                "indexes": [
                    models.Index(
                        fields=["scope_key", "created_at"], name="sales_attempt_scope_idx"
                    ),
                    models.Index(
                        fields=["raw_file_hash", "created_at"], name="sales_attempt_raw_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("row_count__gte", 0)),
                        name="sales_attempt_rows_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("file_size_bytes__gte", 0)),
                        name="sales_attempt_file_size_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesImportFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(default="sales", max_length=32)),
                ("batch_id", models.CharField(max_length=128)),
                ("scope_key", models.CharField(max_length=64)),
                ("scope_json", models.JSONField(default=dict)),
                ("import_hash", models.CharField(max_length=64)),
                ("raw_file_hash", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("row_count", models.BigIntegerField()),
                ("status", models.CharField(default="completed", max_length=32)),
                ("publication_sequence", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sales_import_fingerprints",
                "indexes": [
                    models.Index(
                        fields=["domain", "scope_key", "publication_sequence"],
                        name="sales_fingerprint_scope_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "batch_id"),
                        name="uniq_sales_fingerprint_batch",
                    ),
                    models.UniqueConstraint(
                        fields=("domain", "scope_key", "import_hash"),
                        name="uniq_sales_fingerprint_import",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("row_count__gte", 0)),
                        name="sales_fingerprint_rows_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesImportScopeHead",
            fields=[
                (
                    "scope_key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(default="sales", max_length=32)),
                ("state_token", models.CharField(default="initial", max_length=64)),
                ("status", models.CharField(default="ready", max_length=32)),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                (
                    "current_batch_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("generation", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sales_import_scope_heads",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ready", "processing"])),
                        name="sales_scope_head_status_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("generation__gte", 0)),
                        name="sales_scope_head_generation_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesRawUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_fingerprint", models.CharField(db_index=True, max_length=255)),
                ("actor_email", models.CharField(max_length=320)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField()),
                ("chunk_size_bytes", models.BigIntegerField()),
                ("chunk_count", models.PositiveIntegerField()),
                ("received_chunk_count", models.PositiveIntegerField(default=0)),
                ("received_bytes", models.BigIntegerField(default=0)),
                ("expected_start_date", models.DateField()),
                ("expected_end_date", models.DateField()),
                ("expected_channels", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="uploading", max_length=32)),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("owner_generation", models.BigIntegerField(default=0)),
                ("result_batch_id", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "sales_raw_upload_sessions",
                "indexes": [
                    models.Index(
                        fields=["client_fingerprint", "expires_at"],
                        name="sales_raw_fprint_idx",
                    ),
                    models.Index(fields=["expires_at"], name="sales_raw_upload_expiry_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("file_size_bytes__gt", 0)),
                        name="sales_raw_upload_size_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chunk_size_bytes__gt", 0)),
                        name="sales_raw_chunk_size_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chunk_count__gt", 0)),
                        name="sales_raw_chunk_count_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("received_chunk_count__gte", 0)),
                        name="sales_raw_received_count_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("received_bytes__gte", 0)),
                        name="sales_raw_received_bytes_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesStagedImportSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_fingerprint", models.CharField(db_index=True, max_length=255)),
                ("actor_email", models.CharField(max_length=320)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField()),
                ("raw_file_hash", models.CharField(db_index=True, max_length=64)),
                ("sheet_name", models.CharField(max_length=255)),
                ("expected_start_date", models.DateField()),
                ("expected_end_date", models.DateField()),
                ("expected_channels", models.JSONField(blank=True, null=True)),
                ("chunk_count", models.PositiveIntegerField()),
                ("received_chunk_count", models.PositiveIntegerField(default=0)),
                ("received_row_count", models.PositiveIntegerField(default=0)),
                ("source_totals", models.JSONField(default=dict)),
                ("parser_warnings", models.JSONField(default=list)),
                ("system_cost_snapshot", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="uploading", max_length=32)),
                ("owner_token", models.CharField(blank=True, default="", max_length=64)),
                ("raw_upload_owner_generation", models.BigIntegerField(default=0)),
                (
                    "result_batch_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "raw_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_imports",
                        to="sales.salesrawuploadsession",
                    ),
                ),
                (
                    "raw_upload_owner_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={"db_table": "sales_staged_import_sessions"},
        ),
        migrations.CreateModel(
            name="SalesStagedImportChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("row_count", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("rows", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="sales.salesstagedimportsession",
                    ),
                ),
            ],
            options={"db_table": "sales_staged_import_chunks"},
        ),
        migrations.CreateModel(
            name="SalesWriteAuthority",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=16)),
                ("authority_epoch", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("cutover_id", models.CharField(blank=True, default="", max_length=128)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sales_write_authority",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="sales_auth_singleton_ck"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["pending", "active", "disabled"])
                        ),
                        name="sales_auth_status_ck",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_pending_sales_write_authority,
            delete_pending_sales_write_authority,
        ),
        migrations.CreateModel(
            name="SalesWriteRequestReceipt",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("actor_email", models.CharField(max_length=320)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("body_sha256", models.CharField(max_length=64)),
                ("claim_token", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(default="processing", max_length=16)),
                ("response_status", models.PositiveSmallIntegerField(default=0)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "sales_write_request_receipts",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="sales_write_receipt_expiry_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["processing", "completed", "failed"])
                        ),
                        name="sales_write_receipt_status_ck",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesRawUploadChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("object_key", models.TextField(unique=True)),
                ("size_bytes", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="sales.salesrawuploadsession",
                    ),
                ),
            ],
            options={
                "db_table": "sales_raw_upload_chunks",
                "indexes": [
                    models.Index(
                        fields=["session", "chunk_index"],
                        name="sales_raw_chunk_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "chunk_index"),
                        name="uniq_sales_raw_upload_chunk",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__gt", 0)),
                        name="sales_raw_upload_chunk_size_ck",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="salesstagedimportsession",
            index=models.Index(
                fields=["client_fingerprint", "expires_at"],
                name="sales_stage_fingerprint_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesstagedimportsession",
            index=models.Index(fields=["expires_at"], name="sales_stage_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesstagedimportsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_size_bytes__gt", 0)),
                name="sales_stage_file_size_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesstagedimportsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("chunk_count__gt", 0)),
                name="sales_stage_chunk_count_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesstagedimportsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_chunk_count__gte", 0)),
                name="sales_stage_received_chunks_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesstagedimportsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_row_count__gte", 0)),
                name="sales_stage_received_rows_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="salesstagedimportchunk",
            index=models.Index(
                fields=["session", "chunk_index"],
                name="sales_stage_chunk_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesstagedimportchunk",
            constraint=models.UniqueConstraint(
                fields=("session", "chunk_index"), name="uniq_sales_staged_chunk"
            ),
        ),
    ]
