# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sales", "0006_drop_legacy_projection_checkpoint")]

    operations = [
        migrations.CreateModel(
            name="SalesLegacyUploadAudit",
            fields=[
                (
                    "source_upload_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("source_fingerprint_sha256", models.CharField(max_length=64)),
                ("file_name_sha256", models.CharField(max_length=64)),
                ("file_size_bytes", models.BigIntegerField()),
                ("chunk_size_bytes", models.BigIntegerField()),
                ("declared_chunk_count", models.PositiveIntegerField()),
                ("declared_received_chunk_count", models.PositiveIntegerField()),
                ("declared_received_bytes", models.BigIntegerField()),
                ("source_status", models.CharField(max_length=32)),
                ("archive_reason", models.CharField(max_length=16)),
                ("source_created_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField()),
                ("source_expires_at", models.DateTimeField()),
                ("manifest_chunk_count", models.PositiveIntegerField()),
                ("manifest_bytes", models.BigIntegerField()),
                ("manifest_sha256", models.CharField(max_length=64)),
                (
                    "migration_generation",
                    models.CharField(db_index=True, default="", max_length=64),
                ),
                ("migrated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sales_legacy_upload_audits",
                "indexes": [
                    models.Index(
                        fields=["source_status", "source_expires_at"],
                        name="sales_legacy_status_exp_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_status__in", ["uploading", "ready", "processing", "completed"])
                        ),
                        name="sales_legacy_status_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("archive_reason__in", ["completed", "expired"])),
                        name="sales_legacy_reason_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("archive_reason", "completed"),
                                ("source_status", "completed"),
                            )
                            | (
                                ~models.Q(("source_status", "completed"))
                                & models.Q(("archive_reason", "expired"))
                                & models.Q(
                                    ("source_expires_at__lte", models.F("migrated_at"))
                                )
                            )
                        ),
                        name="sales_legacy_archive_state_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("file_size_bytes__gt", 0)),
                        name="sales_legacy_file_size_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chunk_size_bytes__gt", 0)),
                        name="sales_legacy_chunk_size_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("declared_chunk_count__gt", 0)),
                        name="sales_legacy_decl_count_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("declared_received_bytes__gte", 0)),
                        name="sales_legacy_recv_bytes_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("manifest_bytes__gte", 0)),
                        name="sales_legacy_manifest_bytes_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("declared_received_chunk_count__lte", models.F("declared_chunk_count"))
                        ),
                        name="sales_legacy_recv_le_decl_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manifest_chunk_count__lte", models.F("declared_chunk_count"))
                        ),
                        name="sales_legacy_manifest_le_decl_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("declared_received_bytes__lte", models.F("file_size_bytes"))
                        ),
                        name="sales_legacy_recv_bytes_le_file_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("manifest_bytes__lte", models.F("file_size_bytes"))),
                        name="sales_legacy_manifest_bytes_le_file_ck",
                    ),
                ],
            },
        )
    ]
