# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sales", "0007_legacy_upload_audit")]

    operations = [
        migrations.CreateModel(
            name="SalesCutoverAttestation",
            fields=[
                (
                    "cutover_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("d1_authority_epoch", models.BigIntegerField()),
                ("source_path_digest", models.CharField(max_length=64)),
                ("migration_apply_run_id", models.CharField(max_length=64)),
                ("migration_verify_run_id", models.CharField(max_length=64)),
                ("cleanup_manifest_id", models.CharField(max_length=64)),
                ("cleanup_manifest_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("payload_sha256", models.CharField(max_length=64, unique=True)),
                ("observed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sales_cutover_attestations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("d1_authority_epoch__gte", 1)),
                        name="sales_cutover_d1_epoch_ck",
                    )
                ],
            },
        )
    ]
