import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { root, validatePorts } from "./launcher.mjs";
const runtime = path.join(root, ".runtime/preview");
const session = JSON.parse(readFileSync(path.join(runtime, "session.json"), "utf8"));
const { port, control } = validatePorts(session.port);
const status = await fetch(`http://127.0.0.1:${control}/status`, { headers: { authorization: `Bearer ${session.token}` }, signal: AbortSignal.timeout(2000) });
assert.equal(status.status, 200);
assert.equal((await status.json()).status, "ready");
const base = `http://127.0.0.1:${port}`;
const checks = [];
async function query(route, expected = 200, method = "GET") {
    const response = await fetch(base + route, { method, signal: AbortSignal.timeout(20000) });
    assert.equal(response.status, expected, route);
    checks.push({ route, method, status: response.status });
    return response;
}
const page = await query("/");
assert.match(await page.text(), /演示预览/);
assert.match(page.headers.get("content-security-policy"), /frame-src 'none'/);
const stock = await (await query("/api/inventory/overview?pageSize=5")).json();
assert.equal(stock.metrics.skuWarehouseCount, 6);
assert.equal(stock.metrics.totalAvailableQuantity, 828);
const filtered = await (await query("/api/inventory/overview?q=DEMO-002")).json();
assert.equal(filtered.metrics.skuWarehouseCount, 1);
assert.equal(filtered.metrics.totalAvailableQuantity, 8);
const products = await (await query("/api/products/summary?pageSize=5")).json();
assert.equal(products.pagination.total, 6);
assert.equal(products.items.length, 5);
const nextPage = await (await query("/api/products/summary?pageSize=5&page=2")).json();
assert.equal(nextPage.items.length, 1);
const sales = await (await query("/api/sales/data-health")).json();
assert.equal(sales.latestBatch.rowCount, 180);
const chainStatus = await (await query("/api/imports/chain-status")).json();
assert.equal(chainStatus.source, "synthetic_n8n");
assert.equal(chainStatus.timezone, "Asia/Shanghai");
assert.equal(chainStatus.items.length, 11);
await query("/api/imports/chain-status?path=production", 400);
await query("/api/imports/chain-status", 403, "POST");
await query("/api/inventory/settings", 403, "POST");
await query("/_teruisi/local/market-annotation-scheduled", 403);
await query("/api/inventory/overview?unknown=1", 400);
const report = { fixture: "synthetic-v1", checkedAt: new Date().toISOString(), checks };
writeFileSync(path.join(runtime, "smoke.json"), JSON.stringify(report, null, 2) + "\n");
console.log(JSON.stringify(report, null, 2));
