# Generated by Django 5.2.17 on 2026-09-05 00:17

import django.db.models.deletion
import django.utils.timezone
import hashlib
import json
import uuid
from django.db import migrations, models


def seed_control_rows(apps, schema_editor):
    del schema_editor
    Authority = apps.get_model('erp_reference', 'ErpReferenceWriteAuthority')
    ScopeHead = apps.get_model('erp_reference', 'ErpReferenceImportScopeHead')
    Revision = apps.get_model('sales', 'SalesDataRevision')
    Authority.objects.get_or_create(id=1)
    Revision.objects.get_or_create(
        domain='erp',
        defaults={'revision': 0, 'source_digest': '0' * 64},
    )
    for source in ('products', 'combos'):
        scope = json.dumps({'source': source}, sort_keys=True, separators=(',', ':'))
        scope_key = hashlib.sha256(scope.encode()).hexdigest()
        ScopeHead.objects.get_or_create(
            scope_key=scope_key,
            defaults={'source_key': source, 'state_token': '0' * 64},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('erp_reference', '0001_initial'),
        ('sales', '0009_postgres_raw_upload_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpProductMaster',
            fields=[
                ('product_code', models.TextField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('brand', models.TextField(default='')),
                ('specification', models.TextField(default='')),
                ('barcode', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('supplier', models.TextField(default='')),
                ('product_status', models.TextField(default='')),
                ('source_row_number', models.BigIntegerField()),
                ('last_import_batch_id', models.TextField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'erp_product_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceImportScopeHead',
            fields=[
                ('scope_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=16, unique=True)),
                ('state_token', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('status', models.CharField(default='ready', max_length=16)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('generation', models.BigIntegerField(default=0)),
                ('current_batch_id', models.CharField(default='', max_length=128)),
                ('owner_started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_reference_import_scope_heads',
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceMigrationRun',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('source_path_digest', models.CharField(max_length=64)),
                ('source_snapshot_digest', models.CharField(max_length=64)),
                ('target_snapshot_digest', models.CharField(default='', max_length=64)),
                ('source_counts', models.JSONField(default=dict)),
                ('target_counts', models.JSONField(default=dict)),
                ('approved_run_id', models.CharField(default='', max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'erp_reference_migration_runs',
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceWriteRequestReceipt',
            fields=[
                ('request_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(max_length=320)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=300)),
                ('body_sha256', models.CharField(max_length=64)),
                ('query_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('claim_token', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=0)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'erp_reference_write_request_receipts',
            },
        ),
        migrations.CreateModel(
            name='ErpComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_code', models.TextField()),
                ('parent_name', models.TextField(default='')),
                ('child_code', models.TextField()),
                ('child_name', models.TextField(default='')),
                ('child_quantity_milli', models.BigIntegerField()),
                ('source_row_number', models.BigIntegerField()),
                ('last_import_batch_id', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'erp_combo_items',
                'indexes': [models.Index(fields=['parent_code'], name='erp_combo_parent_idx'), models.Index(fields=['child_code'], name='erp_combo_child_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent_code', 'child_code'), name='erp_combo_identity_uq'), models.CheckConstraint(condition=models.Q(('child_quantity_milli__gt', 0)), name='erp_combo_quantity_ck')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceImportAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(default='', max_length=128)),
                ('source_key', models.CharField(default='', max_length=16)),
                ('scope_key', models.CharField(db_index=True, default='', max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('import_hash', models.CharField(default='', max_length=64)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('row_count', models.BigIntegerField(default=0)),
                ('file_name', models.TextField(default='')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('warnings_json', models.JSONField(default=list)),
                ('outcome', models.CharField(max_length=32)),
                ('error_code', models.CharField(default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'erp_reference_import_attempts',
                'indexes': [models.Index(fields=['source_key', 'created_at'], name='erp_attempt_source_idx'), models.Index(fields=['raw_file_hash', 'created_at'], name='erp_attempt_raw_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceImportBatch',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_key', models.CharField(db_index=True, max_length=16)),
                ('source_label', models.CharField(max_length=100)),
                ('file_name', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('published_state_token', models.CharField(default='', max_length=64)),
                ('sheet_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('row_count', models.BigIntegerField(default=0)),
                ('inserted_count', models.BigIntegerField(default=0)),
                ('updated_count', models.BigIntegerField(default=0)),
                ('excluded_count', models.BigIntegerField(default=0)),
                ('warning_count', models.BigIntegerField(default=0)),
                ('warnings_json', models.JSONField(default=list)),
                ('totals_json', models.JSONField(default=dict)),
                ('actor_email', models.CharField(default='', max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'erp_reference_import_batches_pg',
                'indexes': [models.Index(fields=['source_key', 'created_at'], name='erp_batch_source_created_idx'), models.Index(fields=['status', 'completed_at'], name='erp_batch_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'file_hash'), name='erp_batch_source_hash_uq')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceImportFingerprint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=128, unique=True)),
                ('source_key', models.CharField(max_length=16)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('scope_json', models.JSONField(default=dict)),
                ('import_hash', models.CharField(max_length=64)),
                ('raw_file_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('row_count', models.BigIntegerField()),
                ('published_state_token', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('migration_generation', models.CharField(db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'erp_reference_import_fingerprints',
                'constraints': [models.UniqueConstraint(fields=('scope_key', 'import_hash'), name='erp_fingerprint_scope_import_uq')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceRawUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('source_key', models.CharField(max_length=16)),
                ('actor_email', models.CharField(max_length=320)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('chunk_size_bytes', models.BigIntegerField()),
                ('chunk_count', models.PositiveIntegerField()),
                ('received_chunk_count', models.PositiveIntegerField(default=0)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='uploading', max_length=16)),
                ('owner_token', models.CharField(default='', max_length=64)),
                ('owner_generation', models.BigIntegerField(default=0)),
                ('result_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'erp_reference_raw_upload_sessions',
                'indexes': [models.Index(fields=['fingerprint', 'expires_at'], name='erp_upload_fingerprint_idx'), models.Index(fields=['expires_at', 'status'], name='erp_upload_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceWriteAuthority',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='d1', max_length=16)),
                ('authority_epoch', models.UUIDField(blank=True, null=True)),
                ('cutover_id', models.CharField(default='', max_length=128)),
                ('migration_verify_run_id', models.CharField(default='', max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'erp_reference_write_authority',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='erp_auth_singleton_ck'), models.CheckConstraint(condition=models.Q(('status__in', ['d1', 'postgres'])), name='erp_auth_status_ck'), models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('authority_epoch__isnull', True), ('cutover_id', ''), ('status', 'd1')), models.Q(('activated_at__isnull', False), ('authority_epoch__isnull', False), ('status', 'postgres'), models.Q(('cutover_id', ''), _negated=True), models.Q(('migration_verify_run_id', ''), _negated=True)), _connector='OR'), name='erp_auth_state_ck')],
            },
        ),
        migrations.CreateModel(
            name='ErpReferenceRawUploadChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='erp_reference.erpreferencerawuploadsession')),
            ],
            options={
                'db_table': 'erp_reference_raw_upload_chunks',
                'indexes': [models.Index(fields=['session', 'chunk_index'], name='erp_upload_chunk_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'chunk_index'), name='erp_upload_chunk_uq')],
            },
        ),
        migrations.RunPython(seed_control_rows, migrations.RunPython.noop),
    ]
