# Generated by Django 5.2.17 on 2026-09-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_operations_control_row(apps, schema_editor):
    apps.get_model("workflow", "WorkflowOperationsWriteAuthority").objects.get_or_create(
        id=1,
        defaults={"status": "disabled"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_new_product_weekly_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowOperationsMigrationRun',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=24)),
                ('source_path_digest', models.CharField(max_length=64)),
                ('source_snapshot_digest', models.CharField(max_length=64)),
                ('target_snapshot_digest', models.CharField(default='', max_length=64)),
                ('source_counts', models.JSONField(default=dict)),
                ('target_counts', models.JSONField(default=dict)),
                ('approved_run_id', models.CharField(default='', max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_operations_migration_runs',
            },
        ),
        migrations.CreateModel(
            name='WorkflowAttachmentCleanup',
            fields=[
                ('object_key', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(default='', max_length=500)),
                ('enqueued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'workflow_attachment_cleanup_queue',
                'indexes': [models.Index(fields=['updated_at', 'object_key'], name='workflow_attach_cleanup_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowOperationRecord',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=24)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('platform', models.CharField(default='', max_length=80)),
                ('channel', models.CharField(default='', max_length=80)),
                ('shop_name', models.CharField(max_length=160)),
                ('owner', models.CharField(default='', max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(default='')),
                ('source', models.CharField(default='manual', max_length=24)),
                ('source_ref', models.CharField(default='', max_length=300)),
                ('reference_code', models.CharField(default='', max_length=160)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('mutation_token', models.CharField(default='', max_length=128)),
                ('created_by', models.CharField(max_length=320)),
                ('updated_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(default='', max_length=320)),
            ],
            options={
                'db_table': 'workflow_operation_records',
                'indexes': [models.Index(fields=['record_type', 'status', 'occurred_at', 'id'], name='workflow_ops_type_time_idx'), models.Index(fields=['shop_name', 'record_type', 'occurred_at', 'id'], name='workflow_ops_shop_time_idx'), models.Index(fields=['updated_at', 'id'], name='workflow_ops_updated_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('record_type__in', ['inspection', 'review'])), name='workflow_ops_type_ck'), models.CheckConstraint(condition=models.Q(('priority__in', ['high', 'normal', 'low'])), name='workflow_ops_priority_ck'), models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'system', 'import', 'integration'])), name='workflow_ops_source_ck'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_ops_version_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowOperationsWriteAuthority',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='disabled', max_length=16)),
                ('authority_epoch', models.UUIDField(blank=True, null=True)),
                ('cutover_id', models.CharField(default='', max_length=128)),
                ('migration_verify_run_id', models.CharField(default='', max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_operations_write_authority',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='workflow_ops_auth_singleton_ck'), models.CheckConstraint(condition=models.Q(('status__in', ['disabled', 'postgres'])), name='workflow_ops_auth_status_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('work_content', models.TextField(default='')),
                ('category', models.CharField(default='工作计划', max_length=80)),
                ('owner', models.CharField(default='', max_length=120)),
                ('shop_name', models.CharField(default='', max_length=160)),
                ('start_date', models.CharField(default='待排期', max_length=10)),
                ('due_date', models.CharField(default='待排期', max_length=10)),
                ('status', models.CharField(default='待开始', max_length=16)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('mutation_token', models.CharField(default='', max_length=128)),
                ('created_by', models.CharField(max_length=320)),
                ('updated_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(default='', max_length=320)),
            ],
            options={
                'db_table': 'workflow_tasks',
                'indexes': [models.Index(fields=['status', 'created_at'], name='workflow_task_status_idx'), models.Index(fields=['deleted_at', 'id'], name='workflow_task_deleted_idx'), models.Index(fields=['updated_at', 'id'], name='workflow_task_updated_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_task_version_ck'), models.CheckConstraint(condition=models.Q(('status__in', ['待开始', '工作中', '已完成'])), name='workflow_task_status_ck'), models.CheckConstraint(condition=models.Q(('priority__in', ['high', 'normal', 'low'])), name='workflow_task_priority_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskTemplate',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(default='', max_length=500)),
                ('title', models.CharField(default='', max_length=160)),
                ('work_content', models.TextField(default='')),
                ('category', models.CharField(default='工作计划', max_length=80)),
                ('owner', models.CharField(default='', max_length=120)),
                ('shop_name', models.CharField(default='', max_length=160)),
                ('start_offset_days', models.IntegerField(default=0)),
                ('due_offset_days', models.IntegerField(default=0)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('mutation_token', models.CharField(default='', max_length=128)),
                ('created_by', models.CharField(max_length=320)),
                ('updated_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'workflow_task_templates',
                'indexes': [models.Index(fields=['active', 'updated_at', 'id'], name='workflow_template_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_template_version_ck'), models.CheckConstraint(condition=models.Q(('priority__in', ['high', 'normal', 'low'])), name='workflow_template_priority_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowOperationActivity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('actor_email', models.CharField(max_length=320)),
                ('actor_role', models.CharField(max_length=16)),
                ('from_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('to_version', models.PositiveBigIntegerField()),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.workflowoperationrecord')),
            ],
            options={
                'db_table': 'workflow_operation_activities',
                'indexes': [models.Index(fields=['record', 'to_version', 'id'], name='workflow_ops_activity_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['created', 'updated', 'status_changed', 'deleted'])), name='workflow_ops_activity_action_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskActivityLog',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('actor_email', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_task_activity_logs',
                'indexes': [models.Index(fields=['task', 'created_at', 'id'], name='workflow_task_activity_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskAttachment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('created_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_task_attachments',
                'indexes': [models.Index(fields=['task', 'created_at', 'id'], name='workflow_task_attach_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskComment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_task_comments',
                'indexes': [models.Index(fields=['task', 'created_at', 'id'], name='workflow_task_comment_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskEntityLink',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=24)),
                ('entity_id', models.CharField(max_length=240)),
                ('label', models.CharField(max_length=240)),
                ('url', models.URLField(default='', max_length=1000)),
                ('created_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_task_entity_links',
                'indexes': [models.Index(fields=['task', 'created_at', 'id'], name='workflow_task_link_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'entity_type', 'entity_id'), name='workflow_task_link_uq'), models.CheckConstraint(condition=models.Q(('entity_type__in', ['shop', 'product', 'campaign', 'order', 'report', 'url'])), name='workflow_task_link_type_ck')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskReminder',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('note', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_by', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workflow.workflowtask')),
            ],
            options={
                'db_table': 'workflow_task_reminders',
                'indexes': [models.Index(fields=['task', 'status', 'remind_at'], name='workflow_task_reminder_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'dismissed', 'sent'])), name='workflow_task_reminder_status_ck')],
            },
        ),
        migrations.RunPython(seed_operations_control_row, migrations.RunPython.noop),
    ]
